
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  TaxProfile: 'TaxProfile',
  VatItem: 'VatItem',
  QuizQuestion: 'QuizQuestion',
  QuizScore: 'QuizScore',
  ChatSession: 'ChatSession',
  ChatMessage: 'ChatMessage',
  ForumTopic: 'ForumTopic',
  ForumReply: 'ForumReply',
  TaxArticle: 'TaxArticle'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const TaxProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  monthlyIncome: 'monthlyIncome',
  annualGross: 'annualGross',
  rentPaid: 'rentPaid',
  pensionRate: 'pensionRate',
  computedTax: 'computedTax',
  netIncome: 'netIncome',
  isExempt: 'isExempt',
  citExemption: 'citExemption',
  createdAt: 'createdAt'
} as const

export type TaxProfileScalarFieldEnum = (typeof TaxProfileScalarFieldEnum)[keyof typeof TaxProfileScalarFieldEnum]


export const VatItemScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category: 'category',
  status: 'status',
  rate: 'rate',
  createdAt: 'createdAt'
} as const

export type VatItemScalarFieldEnum = (typeof VatItemScalarFieldEnum)[keyof typeof VatItemScalarFieldEnum]


export const QuizQuestionScalarFieldEnum = {
  id: 'id',
  question: 'question',
  options: 'options',
  correctIndex: 'correctIndex',
  explanation: 'explanation',
  createdAt: 'createdAt'
} as const

export type QuizQuestionScalarFieldEnum = (typeof QuizQuestionScalarFieldEnum)[keyof typeof QuizQuestionScalarFieldEnum]


export const QuizScoreScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  score: 'score',
  totalQuestions: 'totalQuestions',
  createdAt: 'createdAt'
} as const

export type QuizScoreScalarFieldEnum = (typeof QuizScoreScalarFieldEnum)[keyof typeof QuizScoreScalarFieldEnum]


export const ChatSessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ChatSessionScalarFieldEnum = (typeof ChatSessionScalarFieldEnum)[keyof typeof ChatSessionScalarFieldEnum]


export const ChatMessageScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  role: 'role',
  content: 'content',
  createdAt: 'createdAt'
} as const

export type ChatMessageScalarFieldEnum = (typeof ChatMessageScalarFieldEnum)[keyof typeof ChatMessageScalarFieldEnum]


export const ForumTopicScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  tags: 'tags',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  upVotes: 'upVotes',
  downVotes: 'downVotes'
} as const

export type ForumTopicScalarFieldEnum = (typeof ForumTopicScalarFieldEnum)[keyof typeof ForumTopicScalarFieldEnum]


export const ForumReplyScalarFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  content: 'content',
  userId: 'userId',
  createdAt: 'createdAt',
  isAccepted: 'isAccepted'
} as const

export type ForumReplyScalarFieldEnum = (typeof ForumReplyScalarFieldEnum)[keyof typeof ForumReplyScalarFieldEnum]


export const TaxArticleScalarFieldEnum = {
  id: 'id',
  title: 'title',
  summary: 'summary',
  content: 'content',
  source: 'source',
  url: 'url',
  isFeatured: 'isFeatured',
  createdAt: 'createdAt'
} as const

export type TaxArticleScalarFieldEnum = (typeof TaxArticleScalarFieldEnum)[keyof typeof TaxArticleScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

