// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    seed: "npx tsx prisma/seed.ts",
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DIRECT_URL"),       // Use the pooled port (6543) for runtime apps// Use the direct port (5432) for running migrations
  },
});