
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ForumTopic` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ForumTopic
 * 
 */
export type ForumTopicModel = runtime.Types.Result.DefaultSelection<Prisma.$ForumTopicPayload>

export type AggregateForumTopic = {
  _count: ForumTopicCountAggregateOutputType | null
  _avg: ForumTopicAvgAggregateOutputType | null
  _sum: ForumTopicSumAggregateOutputType | null
  _min: ForumTopicMinAggregateOutputType | null
  _max: ForumTopicMaxAggregateOutputType | null
}

export type ForumTopicAvgAggregateOutputType = {
  upVotes: number | null
  downVotes: number | null
}

export type ForumTopicSumAggregateOutputType = {
  upVotes: number | null
  downVotes: number | null
}

export type ForumTopicMinAggregateOutputType = {
  id: string | null
  title: string | null
  content: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  upVotes: number | null
  downVotes: number | null
}

export type ForumTopicMaxAggregateOutputType = {
  id: string | null
  title: string | null
  content: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  upVotes: number | null
  downVotes: number | null
}

export type ForumTopicCountAggregateOutputType = {
  id: number
  title: number
  content: number
  tags: number
  userId: number
  createdAt: number
  updatedAt: number
  upVotes: number
  downVotes: number
  _all: number
}


export type ForumTopicAvgAggregateInputType = {
  upVotes?: true
  downVotes?: true
}

export type ForumTopicSumAggregateInputType = {
  upVotes?: true
  downVotes?: true
}

export type ForumTopicMinAggregateInputType = {
  id?: true
  title?: true
  content?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  upVotes?: true
  downVotes?: true
}

export type ForumTopicMaxAggregateInputType = {
  id?: true
  title?: true
  content?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  upVotes?: true
  downVotes?: true
}

export type ForumTopicCountAggregateInputType = {
  id?: true
  title?: true
  content?: true
  tags?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  upVotes?: true
  downVotes?: true
  _all?: true
}

export type ForumTopicAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ForumTopic to aggregate.
   */
  where?: Prisma.ForumTopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumTopics to fetch.
   */
  orderBy?: Prisma.ForumTopicOrderByWithRelationInput | Prisma.ForumTopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ForumTopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumTopics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumTopics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ForumTopics
  **/
  _count?: true | ForumTopicCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ForumTopicAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ForumTopicSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ForumTopicMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ForumTopicMaxAggregateInputType
}

export type GetForumTopicAggregateType<T extends ForumTopicAggregateArgs> = {
      [P in keyof T & keyof AggregateForumTopic]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateForumTopic[P]>
    : Prisma.GetScalarType<T[P], AggregateForumTopic[P]>
}




export type ForumTopicGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ForumTopicWhereInput
  orderBy?: Prisma.ForumTopicOrderByWithAggregationInput | Prisma.ForumTopicOrderByWithAggregationInput[]
  by: Prisma.ForumTopicScalarFieldEnum[] | Prisma.ForumTopicScalarFieldEnum
  having?: Prisma.ForumTopicScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ForumTopicCountAggregateInputType | true
  _avg?: ForumTopicAvgAggregateInputType
  _sum?: ForumTopicSumAggregateInputType
  _min?: ForumTopicMinAggregateInputType
  _max?: ForumTopicMaxAggregateInputType
}

export type ForumTopicGroupByOutputType = {
  id: string
  title: string
  content: string
  tags: runtime.JsonValue
  userId: string
  createdAt: Date
  updatedAt: Date
  upVotes: number
  downVotes: number
  _count: ForumTopicCountAggregateOutputType | null
  _avg: ForumTopicAvgAggregateOutputType | null
  _sum: ForumTopicSumAggregateOutputType | null
  _min: ForumTopicMinAggregateOutputType | null
  _max: ForumTopicMaxAggregateOutputType | null
}

export type GetForumTopicGroupByPayload<T extends ForumTopicGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ForumTopicGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ForumTopicGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ForumTopicGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ForumTopicGroupByOutputType[P]>
      }
    >
  >



export type ForumTopicWhereInput = {
  AND?: Prisma.ForumTopicWhereInput | Prisma.ForumTopicWhereInput[]
  OR?: Prisma.ForumTopicWhereInput[]
  NOT?: Prisma.ForumTopicWhereInput | Prisma.ForumTopicWhereInput[]
  id?: Prisma.StringFilter<"ForumTopic"> | string
  title?: Prisma.StringFilter<"ForumTopic"> | string
  content?: Prisma.StringFilter<"ForumTopic"> | string
  tags?: Prisma.JsonFilter<"ForumTopic">
  userId?: Prisma.StringFilter<"ForumTopic"> | string
  createdAt?: Prisma.DateTimeFilter<"ForumTopic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ForumTopic"> | Date | string
  upVotes?: Prisma.IntFilter<"ForumTopic"> | number
  downVotes?: Prisma.IntFilter<"ForumTopic"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  replies?: Prisma.ForumReplyListRelationFilter
}

export type ForumTopicOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  upVotes?: Prisma.SortOrder
  downVotes?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  replies?: Prisma.ForumReplyOrderByRelationAggregateInput
}

export type ForumTopicWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ForumTopicWhereInput | Prisma.ForumTopicWhereInput[]
  OR?: Prisma.ForumTopicWhereInput[]
  NOT?: Prisma.ForumTopicWhereInput | Prisma.ForumTopicWhereInput[]
  title?: Prisma.StringFilter<"ForumTopic"> | string
  content?: Prisma.StringFilter<"ForumTopic"> | string
  tags?: Prisma.JsonFilter<"ForumTopic">
  userId?: Prisma.StringFilter<"ForumTopic"> | string
  createdAt?: Prisma.DateTimeFilter<"ForumTopic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ForumTopic"> | Date | string
  upVotes?: Prisma.IntFilter<"ForumTopic"> | number
  downVotes?: Prisma.IntFilter<"ForumTopic"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  replies?: Prisma.ForumReplyListRelationFilter
}, "id">

export type ForumTopicOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  upVotes?: Prisma.SortOrder
  downVotes?: Prisma.SortOrder
  _count?: Prisma.ForumTopicCountOrderByAggregateInput
  _avg?: Prisma.ForumTopicAvgOrderByAggregateInput
  _max?: Prisma.ForumTopicMaxOrderByAggregateInput
  _min?: Prisma.ForumTopicMinOrderByAggregateInput
  _sum?: Prisma.ForumTopicSumOrderByAggregateInput
}

export type ForumTopicScalarWhereWithAggregatesInput = {
  AND?: Prisma.ForumTopicScalarWhereWithAggregatesInput | Prisma.ForumTopicScalarWhereWithAggregatesInput[]
  OR?: Prisma.ForumTopicScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ForumTopicScalarWhereWithAggregatesInput | Prisma.ForumTopicScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ForumTopic"> | string
  title?: Prisma.StringWithAggregatesFilter<"ForumTopic"> | string
  content?: Prisma.StringWithAggregatesFilter<"ForumTopic"> | string
  tags?: Prisma.JsonWithAggregatesFilter<"ForumTopic">
  userId?: Prisma.StringWithAggregatesFilter<"ForumTopic"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ForumTopic"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ForumTopic"> | Date | string
  upVotes?: Prisma.IntWithAggregatesFilter<"ForumTopic"> | number
  downVotes?: Prisma.IntWithAggregatesFilter<"ForumTopic"> | number
}

export type ForumTopicCreateInput = {
  id?: string
  title: string
  content: string
  tags: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  upVotes?: number
  downVotes?: number
  user: Prisma.UserCreateNestedOneWithoutForumTopicsInput
  replies?: Prisma.ForumReplyCreateNestedManyWithoutTopicInput
}

export type ForumTopicUncheckedCreateInput = {
  id?: string
  title: string
  content: string
  tags: Prisma.JsonNullValueInput | runtime.InputJsonValue
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  upVotes?: number
  downVotes?: number
  replies?: Prisma.ForumReplyUncheckedCreateNestedManyWithoutTopicInput
}

export type ForumTopicUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  upVotes?: Prisma.IntFieldUpdateOperationsInput | number
  downVotes?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutForumTopicsNestedInput
  replies?: Prisma.ForumReplyUpdateManyWithoutTopicNestedInput
}

export type ForumTopicUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  upVotes?: Prisma.IntFieldUpdateOperationsInput | number
  downVotes?: Prisma.IntFieldUpdateOperationsInput | number
  replies?: Prisma.ForumReplyUncheckedUpdateManyWithoutTopicNestedInput
}

export type ForumTopicCreateManyInput = {
  id?: string
  title: string
  content: string
  tags: Prisma.JsonNullValueInput | runtime.InputJsonValue
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  upVotes?: number
  downVotes?: number
}

export type ForumTopicUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  upVotes?: Prisma.IntFieldUpdateOperationsInput | number
  downVotes?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ForumTopicUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  upVotes?: Prisma.IntFieldUpdateOperationsInput | number
  downVotes?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ForumTopicListRelationFilter = {
  every?: Prisma.ForumTopicWhereInput
  some?: Prisma.ForumTopicWhereInput
  none?: Prisma.ForumTopicWhereInput
}

export type ForumTopicOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ForumTopicCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  upVotes?: Prisma.SortOrder
  downVotes?: Prisma.SortOrder
}

export type ForumTopicAvgOrderByAggregateInput = {
  upVotes?: Prisma.SortOrder
  downVotes?: Prisma.SortOrder
}

export type ForumTopicMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  upVotes?: Prisma.SortOrder
  downVotes?: Prisma.SortOrder
}

export type ForumTopicMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  upVotes?: Prisma.SortOrder
  downVotes?: Prisma.SortOrder
}

export type ForumTopicSumOrderByAggregateInput = {
  upVotes?: Prisma.SortOrder
  downVotes?: Prisma.SortOrder
}

export type ForumTopicScalarRelationFilter = {
  is?: Prisma.ForumTopicWhereInput
  isNot?: Prisma.ForumTopicWhereInput
}

export type ForumTopicCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ForumTopicCreateWithoutUserInput, Prisma.ForumTopicUncheckedCreateWithoutUserInput> | Prisma.ForumTopicCreateWithoutUserInput[] | Prisma.ForumTopicUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ForumTopicCreateOrConnectWithoutUserInput | Prisma.ForumTopicCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ForumTopicCreateManyUserInputEnvelope
  connect?: Prisma.ForumTopicWhereUniqueInput | Prisma.ForumTopicWhereUniqueInput[]
}

export type ForumTopicUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ForumTopicCreateWithoutUserInput, Prisma.ForumTopicUncheckedCreateWithoutUserInput> | Prisma.ForumTopicCreateWithoutUserInput[] | Prisma.ForumTopicUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ForumTopicCreateOrConnectWithoutUserInput | Prisma.ForumTopicCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ForumTopicCreateManyUserInputEnvelope
  connect?: Prisma.ForumTopicWhereUniqueInput | Prisma.ForumTopicWhereUniqueInput[]
}

export type ForumTopicUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ForumTopicCreateWithoutUserInput, Prisma.ForumTopicUncheckedCreateWithoutUserInput> | Prisma.ForumTopicCreateWithoutUserInput[] | Prisma.ForumTopicUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ForumTopicCreateOrConnectWithoutUserInput | Prisma.ForumTopicCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ForumTopicUpsertWithWhereUniqueWithoutUserInput | Prisma.ForumTopicUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ForumTopicCreateManyUserInputEnvelope
  set?: Prisma.ForumTopicWhereUniqueInput | Prisma.ForumTopicWhereUniqueInput[]
  disconnect?: Prisma.ForumTopicWhereUniqueInput | Prisma.ForumTopicWhereUniqueInput[]
  delete?: Prisma.ForumTopicWhereUniqueInput | Prisma.ForumTopicWhereUniqueInput[]
  connect?: Prisma.ForumTopicWhereUniqueInput | Prisma.ForumTopicWhereUniqueInput[]
  update?: Prisma.ForumTopicUpdateWithWhereUniqueWithoutUserInput | Prisma.ForumTopicUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ForumTopicUpdateManyWithWhereWithoutUserInput | Prisma.ForumTopicUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ForumTopicScalarWhereInput | Prisma.ForumTopicScalarWhereInput[]
}

export type ForumTopicUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ForumTopicCreateWithoutUserInput, Prisma.ForumTopicUncheckedCreateWithoutUserInput> | Prisma.ForumTopicCreateWithoutUserInput[] | Prisma.ForumTopicUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ForumTopicCreateOrConnectWithoutUserInput | Prisma.ForumTopicCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ForumTopicUpsertWithWhereUniqueWithoutUserInput | Prisma.ForumTopicUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ForumTopicCreateManyUserInputEnvelope
  set?: Prisma.ForumTopicWhereUniqueInput | Prisma.ForumTopicWhereUniqueInput[]
  disconnect?: Prisma.ForumTopicWhereUniqueInput | Prisma.ForumTopicWhereUniqueInput[]
  delete?: Prisma.ForumTopicWhereUniqueInput | Prisma.ForumTopicWhereUniqueInput[]
  connect?: Prisma.ForumTopicWhereUniqueInput | Prisma.ForumTopicWhereUniqueInput[]
  update?: Prisma.ForumTopicUpdateWithWhereUniqueWithoutUserInput | Prisma.ForumTopicUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ForumTopicUpdateManyWithWhereWithoutUserInput | Prisma.ForumTopicUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ForumTopicScalarWhereInput | Prisma.ForumTopicScalarWhereInput[]
}

export type ForumTopicCreateNestedOneWithoutRepliesInput = {
  create?: Prisma.XOR<Prisma.ForumTopicCreateWithoutRepliesInput, Prisma.ForumTopicUncheckedCreateWithoutRepliesInput>
  connectOrCreate?: Prisma.ForumTopicCreateOrConnectWithoutRepliesInput
  connect?: Prisma.ForumTopicWhereUniqueInput
}

export type ForumTopicUpdateOneRequiredWithoutRepliesNestedInput = {
  create?: Prisma.XOR<Prisma.ForumTopicCreateWithoutRepliesInput, Prisma.ForumTopicUncheckedCreateWithoutRepliesInput>
  connectOrCreate?: Prisma.ForumTopicCreateOrConnectWithoutRepliesInput
  upsert?: Prisma.ForumTopicUpsertWithoutRepliesInput
  connect?: Prisma.ForumTopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ForumTopicUpdateToOneWithWhereWithoutRepliesInput, Prisma.ForumTopicUpdateWithoutRepliesInput>, Prisma.ForumTopicUncheckedUpdateWithoutRepliesInput>
}

export type ForumTopicCreateWithoutUserInput = {
  id?: string
  title: string
  content: string
  tags: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  upVotes?: number
  downVotes?: number
  replies?: Prisma.ForumReplyCreateNestedManyWithoutTopicInput
}

export type ForumTopicUncheckedCreateWithoutUserInput = {
  id?: string
  title: string
  content: string
  tags: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  upVotes?: number
  downVotes?: number
  replies?: Prisma.ForumReplyUncheckedCreateNestedManyWithoutTopicInput
}

export type ForumTopicCreateOrConnectWithoutUserInput = {
  where: Prisma.ForumTopicWhereUniqueInput
  create: Prisma.XOR<Prisma.ForumTopicCreateWithoutUserInput, Prisma.ForumTopicUncheckedCreateWithoutUserInput>
}

export type ForumTopicCreateManyUserInputEnvelope = {
  data: Prisma.ForumTopicCreateManyUserInput | Prisma.ForumTopicCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ForumTopicUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ForumTopicWhereUniqueInput
  update: Prisma.XOR<Prisma.ForumTopicUpdateWithoutUserInput, Prisma.ForumTopicUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ForumTopicCreateWithoutUserInput, Prisma.ForumTopicUncheckedCreateWithoutUserInput>
}

export type ForumTopicUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ForumTopicWhereUniqueInput
  data: Prisma.XOR<Prisma.ForumTopicUpdateWithoutUserInput, Prisma.ForumTopicUncheckedUpdateWithoutUserInput>
}

export type ForumTopicUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ForumTopicScalarWhereInput
  data: Prisma.XOR<Prisma.ForumTopicUpdateManyMutationInput, Prisma.ForumTopicUncheckedUpdateManyWithoutUserInput>
}

export type ForumTopicScalarWhereInput = {
  AND?: Prisma.ForumTopicScalarWhereInput | Prisma.ForumTopicScalarWhereInput[]
  OR?: Prisma.ForumTopicScalarWhereInput[]
  NOT?: Prisma.ForumTopicScalarWhereInput | Prisma.ForumTopicScalarWhereInput[]
  id?: Prisma.StringFilter<"ForumTopic"> | string
  title?: Prisma.StringFilter<"ForumTopic"> | string
  content?: Prisma.StringFilter<"ForumTopic"> | string
  tags?: Prisma.JsonFilter<"ForumTopic">
  userId?: Prisma.StringFilter<"ForumTopic"> | string
  createdAt?: Prisma.DateTimeFilter<"ForumTopic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ForumTopic"> | Date | string
  upVotes?: Prisma.IntFilter<"ForumTopic"> | number
  downVotes?: Prisma.IntFilter<"ForumTopic"> | number
}

export type ForumTopicCreateWithoutRepliesInput = {
  id?: string
  title: string
  content: string
  tags: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  upVotes?: number
  downVotes?: number
  user: Prisma.UserCreateNestedOneWithoutForumTopicsInput
}

export type ForumTopicUncheckedCreateWithoutRepliesInput = {
  id?: string
  title: string
  content: string
  tags: Prisma.JsonNullValueInput | runtime.InputJsonValue
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  upVotes?: number
  downVotes?: number
}

export type ForumTopicCreateOrConnectWithoutRepliesInput = {
  where: Prisma.ForumTopicWhereUniqueInput
  create: Prisma.XOR<Prisma.ForumTopicCreateWithoutRepliesInput, Prisma.ForumTopicUncheckedCreateWithoutRepliesInput>
}

export type ForumTopicUpsertWithoutRepliesInput = {
  update: Prisma.XOR<Prisma.ForumTopicUpdateWithoutRepliesInput, Prisma.ForumTopicUncheckedUpdateWithoutRepliesInput>
  create: Prisma.XOR<Prisma.ForumTopicCreateWithoutRepliesInput, Prisma.ForumTopicUncheckedCreateWithoutRepliesInput>
  where?: Prisma.ForumTopicWhereInput
}

export type ForumTopicUpdateToOneWithWhereWithoutRepliesInput = {
  where?: Prisma.ForumTopicWhereInput
  data: Prisma.XOR<Prisma.ForumTopicUpdateWithoutRepliesInput, Prisma.ForumTopicUncheckedUpdateWithoutRepliesInput>
}

export type ForumTopicUpdateWithoutRepliesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  upVotes?: Prisma.IntFieldUpdateOperationsInput | number
  downVotes?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutForumTopicsNestedInput
}

export type ForumTopicUncheckedUpdateWithoutRepliesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  upVotes?: Prisma.IntFieldUpdateOperationsInput | number
  downVotes?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ForumTopicCreateManyUserInput = {
  id?: string
  title: string
  content: string
  tags: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  upVotes?: number
  downVotes?: number
}

export type ForumTopicUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  upVotes?: Prisma.IntFieldUpdateOperationsInput | number
  downVotes?: Prisma.IntFieldUpdateOperationsInput | number
  replies?: Prisma.ForumReplyUpdateManyWithoutTopicNestedInput
}

export type ForumTopicUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  upVotes?: Prisma.IntFieldUpdateOperationsInput | number
  downVotes?: Prisma.IntFieldUpdateOperationsInput | number
  replies?: Prisma.ForumReplyUncheckedUpdateManyWithoutTopicNestedInput
}

export type ForumTopicUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  upVotes?: Prisma.IntFieldUpdateOperationsInput | number
  downVotes?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type ForumTopicCountOutputType
 */

export type ForumTopicCountOutputType = {
  replies: number
}

export type ForumTopicCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  replies?: boolean | ForumTopicCountOutputTypeCountRepliesArgs
}

/**
 * ForumTopicCountOutputType without action
 */
export type ForumTopicCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopicCountOutputType
   */
  select?: Prisma.ForumTopicCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ForumTopicCountOutputType without action
 */
export type ForumTopicCountOutputTypeCountRepliesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ForumReplyWhereInput
}


export type ForumTopicSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  tags?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  upVotes?: boolean
  downVotes?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  replies?: boolean | Prisma.ForumTopic$repliesArgs<ExtArgs>
  _count?: boolean | Prisma.ForumTopicCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["forumTopic"]>

export type ForumTopicSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  tags?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  upVotes?: boolean
  downVotes?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["forumTopic"]>

export type ForumTopicSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  tags?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  upVotes?: boolean
  downVotes?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["forumTopic"]>

export type ForumTopicSelectScalar = {
  id?: boolean
  title?: boolean
  content?: boolean
  tags?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  upVotes?: boolean
  downVotes?: boolean
}

export type ForumTopicOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "content" | "tags" | "userId" | "createdAt" | "updatedAt" | "upVotes" | "downVotes", ExtArgs["result"]["forumTopic"]>
export type ForumTopicInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  replies?: boolean | Prisma.ForumTopic$repliesArgs<ExtArgs>
  _count?: boolean | Prisma.ForumTopicCountOutputTypeDefaultArgs<ExtArgs>
}
export type ForumTopicIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ForumTopicIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ForumTopicPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ForumTopic"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    replies: Prisma.$ForumReplyPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    content: string
    tags: runtime.JsonValue
    userId: string
    createdAt: Date
    updatedAt: Date
    upVotes: number
    downVotes: number
  }, ExtArgs["result"]["forumTopic"]>
  composites: {}
}

export type ForumTopicGetPayload<S extends boolean | null | undefined | ForumTopicDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ForumTopicPayload, S>

export type ForumTopicCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ForumTopicFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ForumTopicCountAggregateInputType | true
  }

export interface ForumTopicDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ForumTopic'], meta: { name: 'ForumTopic' } }
  /**
   * Find zero or one ForumTopic that matches the filter.
   * @param {ForumTopicFindUniqueArgs} args - Arguments to find a ForumTopic
   * @example
   * // Get one ForumTopic
   * const forumTopic = await prisma.forumTopic.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ForumTopicFindUniqueArgs>(args: Prisma.SelectSubset<T, ForumTopicFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ForumTopicClient<runtime.Types.Result.GetResult<Prisma.$ForumTopicPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ForumTopic that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ForumTopicFindUniqueOrThrowArgs} args - Arguments to find a ForumTopic
   * @example
   * // Get one ForumTopic
   * const forumTopic = await prisma.forumTopic.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ForumTopicFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ForumTopicFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ForumTopicClient<runtime.Types.Result.GetResult<Prisma.$ForumTopicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ForumTopic that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumTopicFindFirstArgs} args - Arguments to find a ForumTopic
   * @example
   * // Get one ForumTopic
   * const forumTopic = await prisma.forumTopic.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ForumTopicFindFirstArgs>(args?: Prisma.SelectSubset<T, ForumTopicFindFirstArgs<ExtArgs>>): Prisma.Prisma__ForumTopicClient<runtime.Types.Result.GetResult<Prisma.$ForumTopicPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ForumTopic that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumTopicFindFirstOrThrowArgs} args - Arguments to find a ForumTopic
   * @example
   * // Get one ForumTopic
   * const forumTopic = await prisma.forumTopic.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ForumTopicFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ForumTopicFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ForumTopicClient<runtime.Types.Result.GetResult<Prisma.$ForumTopicPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ForumTopics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumTopicFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ForumTopics
   * const forumTopics = await prisma.forumTopic.findMany()
   * 
   * // Get first 10 ForumTopics
   * const forumTopics = await prisma.forumTopic.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const forumTopicWithIdOnly = await prisma.forumTopic.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ForumTopicFindManyArgs>(args?: Prisma.SelectSubset<T, ForumTopicFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumTopicPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ForumTopic.
   * @param {ForumTopicCreateArgs} args - Arguments to create a ForumTopic.
   * @example
   * // Create one ForumTopic
   * const ForumTopic = await prisma.forumTopic.create({
   *   data: {
   *     // ... data to create a ForumTopic
   *   }
   * })
   * 
   */
  create<T extends ForumTopicCreateArgs>(args: Prisma.SelectSubset<T, ForumTopicCreateArgs<ExtArgs>>): Prisma.Prisma__ForumTopicClient<runtime.Types.Result.GetResult<Prisma.$ForumTopicPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ForumTopics.
   * @param {ForumTopicCreateManyArgs} args - Arguments to create many ForumTopics.
   * @example
   * // Create many ForumTopics
   * const forumTopic = await prisma.forumTopic.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ForumTopicCreateManyArgs>(args?: Prisma.SelectSubset<T, ForumTopicCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ForumTopics and returns the data saved in the database.
   * @param {ForumTopicCreateManyAndReturnArgs} args - Arguments to create many ForumTopics.
   * @example
   * // Create many ForumTopics
   * const forumTopic = await prisma.forumTopic.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ForumTopics and only return the `id`
   * const forumTopicWithIdOnly = await prisma.forumTopic.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ForumTopicCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ForumTopicCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumTopicPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ForumTopic.
   * @param {ForumTopicDeleteArgs} args - Arguments to delete one ForumTopic.
   * @example
   * // Delete one ForumTopic
   * const ForumTopic = await prisma.forumTopic.delete({
   *   where: {
   *     // ... filter to delete one ForumTopic
   *   }
   * })
   * 
   */
  delete<T extends ForumTopicDeleteArgs>(args: Prisma.SelectSubset<T, ForumTopicDeleteArgs<ExtArgs>>): Prisma.Prisma__ForumTopicClient<runtime.Types.Result.GetResult<Prisma.$ForumTopicPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ForumTopic.
   * @param {ForumTopicUpdateArgs} args - Arguments to update one ForumTopic.
   * @example
   * // Update one ForumTopic
   * const forumTopic = await prisma.forumTopic.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ForumTopicUpdateArgs>(args: Prisma.SelectSubset<T, ForumTopicUpdateArgs<ExtArgs>>): Prisma.Prisma__ForumTopicClient<runtime.Types.Result.GetResult<Prisma.$ForumTopicPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ForumTopics.
   * @param {ForumTopicDeleteManyArgs} args - Arguments to filter ForumTopics to delete.
   * @example
   * // Delete a few ForumTopics
   * const { count } = await prisma.forumTopic.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ForumTopicDeleteManyArgs>(args?: Prisma.SelectSubset<T, ForumTopicDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ForumTopics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumTopicUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ForumTopics
   * const forumTopic = await prisma.forumTopic.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ForumTopicUpdateManyArgs>(args: Prisma.SelectSubset<T, ForumTopicUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ForumTopics and returns the data updated in the database.
   * @param {ForumTopicUpdateManyAndReturnArgs} args - Arguments to update many ForumTopics.
   * @example
   * // Update many ForumTopics
   * const forumTopic = await prisma.forumTopic.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ForumTopics and only return the `id`
   * const forumTopicWithIdOnly = await prisma.forumTopic.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ForumTopicUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ForumTopicUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumTopicPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ForumTopic.
   * @param {ForumTopicUpsertArgs} args - Arguments to update or create a ForumTopic.
   * @example
   * // Update or create a ForumTopic
   * const forumTopic = await prisma.forumTopic.upsert({
   *   create: {
   *     // ... data to create a ForumTopic
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ForumTopic we want to update
   *   }
   * })
   */
  upsert<T extends ForumTopicUpsertArgs>(args: Prisma.SelectSubset<T, ForumTopicUpsertArgs<ExtArgs>>): Prisma.Prisma__ForumTopicClient<runtime.Types.Result.GetResult<Prisma.$ForumTopicPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ForumTopics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumTopicCountArgs} args - Arguments to filter ForumTopics to count.
   * @example
   * // Count the number of ForumTopics
   * const count = await prisma.forumTopic.count({
   *   where: {
   *     // ... the filter for the ForumTopics we want to count
   *   }
   * })
  **/
  count<T extends ForumTopicCountArgs>(
    args?: Prisma.Subset<T, ForumTopicCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ForumTopicCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ForumTopic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumTopicAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ForumTopicAggregateArgs>(args: Prisma.Subset<T, ForumTopicAggregateArgs>): Prisma.PrismaPromise<GetForumTopicAggregateType<T>>

  /**
   * Group by ForumTopic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumTopicGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ForumTopicGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ForumTopicGroupByArgs['orderBy'] }
      : { orderBy?: ForumTopicGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ForumTopicGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetForumTopicGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ForumTopic model
 */
readonly fields: ForumTopicFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ForumTopic.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ForumTopicClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  replies<T extends Prisma.ForumTopic$repliesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ForumTopic$repliesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumReplyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ForumTopic model
 */
export interface ForumTopicFieldRefs {
  readonly id: Prisma.FieldRef<"ForumTopic", 'String'>
  readonly title: Prisma.FieldRef<"ForumTopic", 'String'>
  readonly content: Prisma.FieldRef<"ForumTopic", 'String'>
  readonly tags: Prisma.FieldRef<"ForumTopic", 'Json'>
  readonly userId: Prisma.FieldRef<"ForumTopic", 'String'>
  readonly createdAt: Prisma.FieldRef<"ForumTopic", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ForumTopic", 'DateTime'>
  readonly upVotes: Prisma.FieldRef<"ForumTopic", 'Int'>
  readonly downVotes: Prisma.FieldRef<"ForumTopic", 'Int'>
}
    

// Custom InputTypes
/**
 * ForumTopic findUnique
 */
export type ForumTopicFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopic
   */
  select?: Prisma.ForumTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumTopic
   */
  omit?: Prisma.ForumTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumTopicInclude<ExtArgs> | null
  /**
   * Filter, which ForumTopic to fetch.
   */
  where: Prisma.ForumTopicWhereUniqueInput
}

/**
 * ForumTopic findUniqueOrThrow
 */
export type ForumTopicFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopic
   */
  select?: Prisma.ForumTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumTopic
   */
  omit?: Prisma.ForumTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumTopicInclude<ExtArgs> | null
  /**
   * Filter, which ForumTopic to fetch.
   */
  where: Prisma.ForumTopicWhereUniqueInput
}

/**
 * ForumTopic findFirst
 */
export type ForumTopicFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopic
   */
  select?: Prisma.ForumTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumTopic
   */
  omit?: Prisma.ForumTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumTopicInclude<ExtArgs> | null
  /**
   * Filter, which ForumTopic to fetch.
   */
  where?: Prisma.ForumTopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumTopics to fetch.
   */
  orderBy?: Prisma.ForumTopicOrderByWithRelationInput | Prisma.ForumTopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ForumTopics.
   */
  cursor?: Prisma.ForumTopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumTopics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumTopics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ForumTopics.
   */
  distinct?: Prisma.ForumTopicScalarFieldEnum | Prisma.ForumTopicScalarFieldEnum[]
}

/**
 * ForumTopic findFirstOrThrow
 */
export type ForumTopicFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopic
   */
  select?: Prisma.ForumTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumTopic
   */
  omit?: Prisma.ForumTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumTopicInclude<ExtArgs> | null
  /**
   * Filter, which ForumTopic to fetch.
   */
  where?: Prisma.ForumTopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumTopics to fetch.
   */
  orderBy?: Prisma.ForumTopicOrderByWithRelationInput | Prisma.ForumTopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ForumTopics.
   */
  cursor?: Prisma.ForumTopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumTopics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumTopics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ForumTopics.
   */
  distinct?: Prisma.ForumTopicScalarFieldEnum | Prisma.ForumTopicScalarFieldEnum[]
}

/**
 * ForumTopic findMany
 */
export type ForumTopicFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopic
   */
  select?: Prisma.ForumTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumTopic
   */
  omit?: Prisma.ForumTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumTopicInclude<ExtArgs> | null
  /**
   * Filter, which ForumTopics to fetch.
   */
  where?: Prisma.ForumTopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumTopics to fetch.
   */
  orderBy?: Prisma.ForumTopicOrderByWithRelationInput | Prisma.ForumTopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ForumTopics.
   */
  cursor?: Prisma.ForumTopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumTopics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumTopics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ForumTopics.
   */
  distinct?: Prisma.ForumTopicScalarFieldEnum | Prisma.ForumTopicScalarFieldEnum[]
}

/**
 * ForumTopic create
 */
export type ForumTopicCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopic
   */
  select?: Prisma.ForumTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumTopic
   */
  omit?: Prisma.ForumTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumTopicInclude<ExtArgs> | null
  /**
   * The data needed to create a ForumTopic.
   */
  data: Prisma.XOR<Prisma.ForumTopicCreateInput, Prisma.ForumTopicUncheckedCreateInput>
}

/**
 * ForumTopic createMany
 */
export type ForumTopicCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ForumTopics.
   */
  data: Prisma.ForumTopicCreateManyInput | Prisma.ForumTopicCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ForumTopic createManyAndReturn
 */
export type ForumTopicCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopic
   */
  select?: Prisma.ForumTopicSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ForumTopic
   */
  omit?: Prisma.ForumTopicOmit<ExtArgs> | null
  /**
   * The data used to create many ForumTopics.
   */
  data: Prisma.ForumTopicCreateManyInput | Prisma.ForumTopicCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumTopicIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ForumTopic update
 */
export type ForumTopicUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopic
   */
  select?: Prisma.ForumTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumTopic
   */
  omit?: Prisma.ForumTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumTopicInclude<ExtArgs> | null
  /**
   * The data needed to update a ForumTopic.
   */
  data: Prisma.XOR<Prisma.ForumTopicUpdateInput, Prisma.ForumTopicUncheckedUpdateInput>
  /**
   * Choose, which ForumTopic to update.
   */
  where: Prisma.ForumTopicWhereUniqueInput
}

/**
 * ForumTopic updateMany
 */
export type ForumTopicUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ForumTopics.
   */
  data: Prisma.XOR<Prisma.ForumTopicUpdateManyMutationInput, Prisma.ForumTopicUncheckedUpdateManyInput>
  /**
   * Filter which ForumTopics to update
   */
  where?: Prisma.ForumTopicWhereInput
  /**
   * Limit how many ForumTopics to update.
   */
  limit?: number
}

/**
 * ForumTopic updateManyAndReturn
 */
export type ForumTopicUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopic
   */
  select?: Prisma.ForumTopicSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ForumTopic
   */
  omit?: Prisma.ForumTopicOmit<ExtArgs> | null
  /**
   * The data used to update ForumTopics.
   */
  data: Prisma.XOR<Prisma.ForumTopicUpdateManyMutationInput, Prisma.ForumTopicUncheckedUpdateManyInput>
  /**
   * Filter which ForumTopics to update
   */
  where?: Prisma.ForumTopicWhereInput
  /**
   * Limit how many ForumTopics to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumTopicIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ForumTopic upsert
 */
export type ForumTopicUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopic
   */
  select?: Prisma.ForumTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumTopic
   */
  omit?: Prisma.ForumTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumTopicInclude<ExtArgs> | null
  /**
   * The filter to search for the ForumTopic to update in case it exists.
   */
  where: Prisma.ForumTopicWhereUniqueInput
  /**
   * In case the ForumTopic found by the `where` argument doesn't exist, create a new ForumTopic with this data.
   */
  create: Prisma.XOR<Prisma.ForumTopicCreateInput, Prisma.ForumTopicUncheckedCreateInput>
  /**
   * In case the ForumTopic was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ForumTopicUpdateInput, Prisma.ForumTopicUncheckedUpdateInput>
}

/**
 * ForumTopic delete
 */
export type ForumTopicDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopic
   */
  select?: Prisma.ForumTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumTopic
   */
  omit?: Prisma.ForumTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumTopicInclude<ExtArgs> | null
  /**
   * Filter which ForumTopic to delete.
   */
  where: Prisma.ForumTopicWhereUniqueInput
}

/**
 * ForumTopic deleteMany
 */
export type ForumTopicDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ForumTopics to delete
   */
  where?: Prisma.ForumTopicWhereInput
  /**
   * Limit how many ForumTopics to delete.
   */
  limit?: number
}

/**
 * ForumTopic.replies
 */
export type ForumTopic$repliesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumReply
   */
  select?: Prisma.ForumReplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumReply
   */
  omit?: Prisma.ForumReplyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumReplyInclude<ExtArgs> | null
  where?: Prisma.ForumReplyWhereInput
  orderBy?: Prisma.ForumReplyOrderByWithRelationInput | Prisma.ForumReplyOrderByWithRelationInput[]
  cursor?: Prisma.ForumReplyWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ForumReplyScalarFieldEnum | Prisma.ForumReplyScalarFieldEnum[]
}

/**
 * ForumTopic without action
 */
export type ForumTopicDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumTopic
   */
  select?: Prisma.ForumTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumTopic
   */
  omit?: Prisma.ForumTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumTopicInclude<ExtArgs> | null
}
