
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuizScore` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model QuizScore
 * 
 */
export type QuizScoreModel = runtime.Types.Result.DefaultSelection<Prisma.$QuizScorePayload>

export type AggregateQuizScore = {
  _count: QuizScoreCountAggregateOutputType | null
  _avg: QuizScoreAvgAggregateOutputType | null
  _sum: QuizScoreSumAggregateOutputType | null
  _min: QuizScoreMinAggregateOutputType | null
  _max: QuizScoreMaxAggregateOutputType | null
}

export type QuizScoreAvgAggregateOutputType = {
  score: number | null
  totalQuestions: number | null
}

export type QuizScoreSumAggregateOutputType = {
  score: number | null
  totalQuestions: number | null
}

export type QuizScoreMinAggregateOutputType = {
  id: string | null
  userId: string | null
  score: number | null
  totalQuestions: number | null
  createdAt: Date | null
}

export type QuizScoreMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  score: number | null
  totalQuestions: number | null
  createdAt: Date | null
}

export type QuizScoreCountAggregateOutputType = {
  id: number
  userId: number
  score: number
  totalQuestions: number
  createdAt: number
  _all: number
}


export type QuizScoreAvgAggregateInputType = {
  score?: true
  totalQuestions?: true
}

export type QuizScoreSumAggregateInputType = {
  score?: true
  totalQuestions?: true
}

export type QuizScoreMinAggregateInputType = {
  id?: true
  userId?: true
  score?: true
  totalQuestions?: true
  createdAt?: true
}

export type QuizScoreMaxAggregateInputType = {
  id?: true
  userId?: true
  score?: true
  totalQuestions?: true
  createdAt?: true
}

export type QuizScoreCountAggregateInputType = {
  id?: true
  userId?: true
  score?: true
  totalQuestions?: true
  createdAt?: true
  _all?: true
}

export type QuizScoreAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizScore to aggregate.
   */
  where?: Prisma.QuizScoreWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizScores to fetch.
   */
  orderBy?: Prisma.QuizScoreOrderByWithRelationInput | Prisma.QuizScoreOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuizScoreWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizScores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizScores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuizScores
  **/
  _count?: true | QuizScoreCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: QuizScoreAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: QuizScoreSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuizScoreMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuizScoreMaxAggregateInputType
}

export type GetQuizScoreAggregateType<T extends QuizScoreAggregateArgs> = {
      [P in keyof T & keyof AggregateQuizScore]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuizScore[P]>
    : Prisma.GetScalarType<T[P], AggregateQuizScore[P]>
}




export type QuizScoreGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuizScoreWhereInput
  orderBy?: Prisma.QuizScoreOrderByWithAggregationInput | Prisma.QuizScoreOrderByWithAggregationInput[]
  by: Prisma.QuizScoreScalarFieldEnum[] | Prisma.QuizScoreScalarFieldEnum
  having?: Prisma.QuizScoreScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuizScoreCountAggregateInputType | true
  _avg?: QuizScoreAvgAggregateInputType
  _sum?: QuizScoreSumAggregateInputType
  _min?: QuizScoreMinAggregateInputType
  _max?: QuizScoreMaxAggregateInputType
}

export type QuizScoreGroupByOutputType = {
  id: string
  userId: string
  score: number
  totalQuestions: number
  createdAt: Date
  _count: QuizScoreCountAggregateOutputType | null
  _avg: QuizScoreAvgAggregateOutputType | null
  _sum: QuizScoreSumAggregateOutputType | null
  _min: QuizScoreMinAggregateOutputType | null
  _max: QuizScoreMaxAggregateOutputType | null
}

export type GetQuizScoreGroupByPayload<T extends QuizScoreGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuizScoreGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuizScoreGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuizScoreGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuizScoreGroupByOutputType[P]>
      }
    >
  >



export type QuizScoreWhereInput = {
  AND?: Prisma.QuizScoreWhereInput | Prisma.QuizScoreWhereInput[]
  OR?: Prisma.QuizScoreWhereInput[]
  NOT?: Prisma.QuizScoreWhereInput | Prisma.QuizScoreWhereInput[]
  id?: Prisma.StringFilter<"QuizScore"> | string
  userId?: Prisma.StringFilter<"QuizScore"> | string
  score?: Prisma.IntFilter<"QuizScore"> | number
  totalQuestions?: Prisma.IntFilter<"QuizScore"> | number
  createdAt?: Prisma.DateTimeFilter<"QuizScore"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type QuizScoreOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  totalQuestions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type QuizScoreWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.QuizScoreWhereInput | Prisma.QuizScoreWhereInput[]
  OR?: Prisma.QuizScoreWhereInput[]
  NOT?: Prisma.QuizScoreWhereInput | Prisma.QuizScoreWhereInput[]
  userId?: Prisma.StringFilter<"QuizScore"> | string
  score?: Prisma.IntFilter<"QuizScore"> | number
  totalQuestions?: Prisma.IntFilter<"QuizScore"> | number
  createdAt?: Prisma.DateTimeFilter<"QuizScore"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type QuizScoreOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  totalQuestions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.QuizScoreCountOrderByAggregateInput
  _avg?: Prisma.QuizScoreAvgOrderByAggregateInput
  _max?: Prisma.QuizScoreMaxOrderByAggregateInput
  _min?: Prisma.QuizScoreMinOrderByAggregateInput
  _sum?: Prisma.QuizScoreSumOrderByAggregateInput
}

export type QuizScoreScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuizScoreScalarWhereWithAggregatesInput | Prisma.QuizScoreScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuizScoreScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuizScoreScalarWhereWithAggregatesInput | Prisma.QuizScoreScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QuizScore"> | string
  userId?: Prisma.StringWithAggregatesFilter<"QuizScore"> | string
  score?: Prisma.IntWithAggregatesFilter<"QuizScore"> | number
  totalQuestions?: Prisma.IntWithAggregatesFilter<"QuizScore"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"QuizScore"> | Date | string
}

export type QuizScoreCreateInput = {
  id?: string
  score: number
  totalQuestions: number
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutQuizScoresInput
}

export type QuizScoreUncheckedCreateInput = {
  id?: string
  userId: string
  score: number
  totalQuestions: number
  createdAt?: Date | string
}

export type QuizScoreUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  totalQuestions?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutQuizScoresNestedInput
}

export type QuizScoreUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  totalQuestions?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizScoreCreateManyInput = {
  id?: string
  userId: string
  score: number
  totalQuestions: number
  createdAt?: Date | string
}

export type QuizScoreUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  totalQuestions?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizScoreUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  totalQuestions?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizScoreListRelationFilter = {
  every?: Prisma.QuizScoreWhereInput
  some?: Prisma.QuizScoreWhereInput
  none?: Prisma.QuizScoreWhereInput
}

export type QuizScoreOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuizScoreCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  totalQuestions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type QuizScoreAvgOrderByAggregateInput = {
  score?: Prisma.SortOrder
  totalQuestions?: Prisma.SortOrder
}

export type QuizScoreMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  totalQuestions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type QuizScoreMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  totalQuestions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type QuizScoreSumOrderByAggregateInput = {
  score?: Prisma.SortOrder
  totalQuestions?: Prisma.SortOrder
}

export type QuizScoreCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.QuizScoreCreateWithoutUserInput, Prisma.QuizScoreUncheckedCreateWithoutUserInput> | Prisma.QuizScoreCreateWithoutUserInput[] | Prisma.QuizScoreUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuizScoreCreateOrConnectWithoutUserInput | Prisma.QuizScoreCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.QuizScoreCreateManyUserInputEnvelope
  connect?: Prisma.QuizScoreWhereUniqueInput | Prisma.QuizScoreWhereUniqueInput[]
}

export type QuizScoreUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.QuizScoreCreateWithoutUserInput, Prisma.QuizScoreUncheckedCreateWithoutUserInput> | Prisma.QuizScoreCreateWithoutUserInput[] | Prisma.QuizScoreUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuizScoreCreateOrConnectWithoutUserInput | Prisma.QuizScoreCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.QuizScoreCreateManyUserInputEnvelope
  connect?: Prisma.QuizScoreWhereUniqueInput | Prisma.QuizScoreWhereUniqueInput[]
}

export type QuizScoreUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.QuizScoreCreateWithoutUserInput, Prisma.QuizScoreUncheckedCreateWithoutUserInput> | Prisma.QuizScoreCreateWithoutUserInput[] | Prisma.QuizScoreUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuizScoreCreateOrConnectWithoutUserInput | Prisma.QuizScoreCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.QuizScoreUpsertWithWhereUniqueWithoutUserInput | Prisma.QuizScoreUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.QuizScoreCreateManyUserInputEnvelope
  set?: Prisma.QuizScoreWhereUniqueInput | Prisma.QuizScoreWhereUniqueInput[]
  disconnect?: Prisma.QuizScoreWhereUniqueInput | Prisma.QuizScoreWhereUniqueInput[]
  delete?: Prisma.QuizScoreWhereUniqueInput | Prisma.QuizScoreWhereUniqueInput[]
  connect?: Prisma.QuizScoreWhereUniqueInput | Prisma.QuizScoreWhereUniqueInput[]
  update?: Prisma.QuizScoreUpdateWithWhereUniqueWithoutUserInput | Prisma.QuizScoreUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.QuizScoreUpdateManyWithWhereWithoutUserInput | Prisma.QuizScoreUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.QuizScoreScalarWhereInput | Prisma.QuizScoreScalarWhereInput[]
}

export type QuizScoreUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.QuizScoreCreateWithoutUserInput, Prisma.QuizScoreUncheckedCreateWithoutUserInput> | Prisma.QuizScoreCreateWithoutUserInput[] | Prisma.QuizScoreUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuizScoreCreateOrConnectWithoutUserInput | Prisma.QuizScoreCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.QuizScoreUpsertWithWhereUniqueWithoutUserInput | Prisma.QuizScoreUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.QuizScoreCreateManyUserInputEnvelope
  set?: Prisma.QuizScoreWhereUniqueInput | Prisma.QuizScoreWhereUniqueInput[]
  disconnect?: Prisma.QuizScoreWhereUniqueInput | Prisma.QuizScoreWhereUniqueInput[]
  delete?: Prisma.QuizScoreWhereUniqueInput | Prisma.QuizScoreWhereUniqueInput[]
  connect?: Prisma.QuizScoreWhereUniqueInput | Prisma.QuizScoreWhereUniqueInput[]
  update?: Prisma.QuizScoreUpdateWithWhereUniqueWithoutUserInput | Prisma.QuizScoreUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.QuizScoreUpdateManyWithWhereWithoutUserInput | Prisma.QuizScoreUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.QuizScoreScalarWhereInput | Prisma.QuizScoreScalarWhereInput[]
}

export type QuizScoreCreateWithoutUserInput = {
  id?: string
  score: number
  totalQuestions: number
  createdAt?: Date | string
}

export type QuizScoreUncheckedCreateWithoutUserInput = {
  id?: string
  score: number
  totalQuestions: number
  createdAt?: Date | string
}

export type QuizScoreCreateOrConnectWithoutUserInput = {
  where: Prisma.QuizScoreWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizScoreCreateWithoutUserInput, Prisma.QuizScoreUncheckedCreateWithoutUserInput>
}

export type QuizScoreCreateManyUserInputEnvelope = {
  data: Prisma.QuizScoreCreateManyUserInput | Prisma.QuizScoreCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type QuizScoreUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.QuizScoreWhereUniqueInput
  update: Prisma.XOR<Prisma.QuizScoreUpdateWithoutUserInput, Prisma.QuizScoreUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.QuizScoreCreateWithoutUserInput, Prisma.QuizScoreUncheckedCreateWithoutUserInput>
}

export type QuizScoreUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.QuizScoreWhereUniqueInput
  data: Prisma.XOR<Prisma.QuizScoreUpdateWithoutUserInput, Prisma.QuizScoreUncheckedUpdateWithoutUserInput>
}

export type QuizScoreUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.QuizScoreScalarWhereInput
  data: Prisma.XOR<Prisma.QuizScoreUpdateManyMutationInput, Prisma.QuizScoreUncheckedUpdateManyWithoutUserInput>
}

export type QuizScoreScalarWhereInput = {
  AND?: Prisma.QuizScoreScalarWhereInput | Prisma.QuizScoreScalarWhereInput[]
  OR?: Prisma.QuizScoreScalarWhereInput[]
  NOT?: Prisma.QuizScoreScalarWhereInput | Prisma.QuizScoreScalarWhereInput[]
  id?: Prisma.StringFilter<"QuizScore"> | string
  userId?: Prisma.StringFilter<"QuizScore"> | string
  score?: Prisma.IntFilter<"QuizScore"> | number
  totalQuestions?: Prisma.IntFilter<"QuizScore"> | number
  createdAt?: Prisma.DateTimeFilter<"QuizScore"> | Date | string
}

export type QuizScoreCreateManyUserInput = {
  id?: string
  score: number
  totalQuestions: number
  createdAt?: Date | string
}

export type QuizScoreUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  totalQuestions?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizScoreUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  totalQuestions?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizScoreUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  totalQuestions?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type QuizScoreSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  score?: boolean
  totalQuestions?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizScore"]>

export type QuizScoreSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  score?: boolean
  totalQuestions?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizScore"]>

export type QuizScoreSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  score?: boolean
  totalQuestions?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizScore"]>

export type QuizScoreSelectScalar = {
  id?: boolean
  userId?: boolean
  score?: boolean
  totalQuestions?: boolean
  createdAt?: boolean
}

export type QuizScoreOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "score" | "totalQuestions" | "createdAt", ExtArgs["result"]["quizScore"]>
export type QuizScoreInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type QuizScoreIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type QuizScoreIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $QuizScorePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuizScore"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    score: number
    totalQuestions: number
    createdAt: Date
  }, ExtArgs["result"]["quizScore"]>
  composites: {}
}

export type QuizScoreGetPayload<S extends boolean | null | undefined | QuizScoreDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuizScorePayload, S>

export type QuizScoreCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuizScoreFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuizScoreCountAggregateInputType | true
  }

export interface QuizScoreDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuizScore'], meta: { name: 'QuizScore' } }
  /**
   * Find zero or one QuizScore that matches the filter.
   * @param {QuizScoreFindUniqueArgs} args - Arguments to find a QuizScore
   * @example
   * // Get one QuizScore
   * const quizScore = await prisma.quizScore.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuizScoreFindUniqueArgs>(args: Prisma.SelectSubset<T, QuizScoreFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuizScoreClient<runtime.Types.Result.GetResult<Prisma.$QuizScorePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuizScore that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuizScoreFindUniqueOrThrowArgs} args - Arguments to find a QuizScore
   * @example
   * // Get one QuizScore
   * const quizScore = await prisma.quizScore.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuizScoreFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuizScoreFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizScoreClient<runtime.Types.Result.GetResult<Prisma.$QuizScorePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizScore that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizScoreFindFirstArgs} args - Arguments to find a QuizScore
   * @example
   * // Get one QuizScore
   * const quizScore = await prisma.quizScore.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuizScoreFindFirstArgs>(args?: Prisma.SelectSubset<T, QuizScoreFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuizScoreClient<runtime.Types.Result.GetResult<Prisma.$QuizScorePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizScore that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizScoreFindFirstOrThrowArgs} args - Arguments to find a QuizScore
   * @example
   * // Get one QuizScore
   * const quizScore = await prisma.quizScore.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuizScoreFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuizScoreFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizScoreClient<runtime.Types.Result.GetResult<Prisma.$QuizScorePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuizScores that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizScoreFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuizScores
   * const quizScores = await prisma.quizScore.findMany()
   * 
   * // Get first 10 QuizScores
   * const quizScores = await prisma.quizScore.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const quizScoreWithIdOnly = await prisma.quizScore.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuizScoreFindManyArgs>(args?: Prisma.SelectSubset<T, QuizScoreFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizScorePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuizScore.
   * @param {QuizScoreCreateArgs} args - Arguments to create a QuizScore.
   * @example
   * // Create one QuizScore
   * const QuizScore = await prisma.quizScore.create({
   *   data: {
   *     // ... data to create a QuizScore
   *   }
   * })
   * 
   */
  create<T extends QuizScoreCreateArgs>(args: Prisma.SelectSubset<T, QuizScoreCreateArgs<ExtArgs>>): Prisma.Prisma__QuizScoreClient<runtime.Types.Result.GetResult<Prisma.$QuizScorePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuizScores.
   * @param {QuizScoreCreateManyArgs} args - Arguments to create many QuizScores.
   * @example
   * // Create many QuizScores
   * const quizScore = await prisma.quizScore.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuizScoreCreateManyArgs>(args?: Prisma.SelectSubset<T, QuizScoreCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuizScores and returns the data saved in the database.
   * @param {QuizScoreCreateManyAndReturnArgs} args - Arguments to create many QuizScores.
   * @example
   * // Create many QuizScores
   * const quizScore = await prisma.quizScore.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuizScores and only return the `id`
   * const quizScoreWithIdOnly = await prisma.quizScore.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuizScoreCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuizScoreCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizScorePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuizScore.
   * @param {QuizScoreDeleteArgs} args - Arguments to delete one QuizScore.
   * @example
   * // Delete one QuizScore
   * const QuizScore = await prisma.quizScore.delete({
   *   where: {
   *     // ... filter to delete one QuizScore
   *   }
   * })
   * 
   */
  delete<T extends QuizScoreDeleteArgs>(args: Prisma.SelectSubset<T, QuizScoreDeleteArgs<ExtArgs>>): Prisma.Prisma__QuizScoreClient<runtime.Types.Result.GetResult<Prisma.$QuizScorePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuizScore.
   * @param {QuizScoreUpdateArgs} args - Arguments to update one QuizScore.
   * @example
   * // Update one QuizScore
   * const quizScore = await prisma.quizScore.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuizScoreUpdateArgs>(args: Prisma.SelectSubset<T, QuizScoreUpdateArgs<ExtArgs>>): Prisma.Prisma__QuizScoreClient<runtime.Types.Result.GetResult<Prisma.$QuizScorePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuizScores.
   * @param {QuizScoreDeleteManyArgs} args - Arguments to filter QuizScores to delete.
   * @example
   * // Delete a few QuizScores
   * const { count } = await prisma.quizScore.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuizScoreDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuizScoreDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizScores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizScoreUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuizScores
   * const quizScore = await prisma.quizScore.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuizScoreUpdateManyArgs>(args: Prisma.SelectSubset<T, QuizScoreUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizScores and returns the data updated in the database.
   * @param {QuizScoreUpdateManyAndReturnArgs} args - Arguments to update many QuizScores.
   * @example
   * // Update many QuizScores
   * const quizScore = await prisma.quizScore.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuizScores and only return the `id`
   * const quizScoreWithIdOnly = await prisma.quizScore.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuizScoreUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuizScoreUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizScorePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuizScore.
   * @param {QuizScoreUpsertArgs} args - Arguments to update or create a QuizScore.
   * @example
   * // Update or create a QuizScore
   * const quizScore = await prisma.quizScore.upsert({
   *   create: {
   *     // ... data to create a QuizScore
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuizScore we want to update
   *   }
   * })
   */
  upsert<T extends QuizScoreUpsertArgs>(args: Prisma.SelectSubset<T, QuizScoreUpsertArgs<ExtArgs>>): Prisma.Prisma__QuizScoreClient<runtime.Types.Result.GetResult<Prisma.$QuizScorePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuizScores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizScoreCountArgs} args - Arguments to filter QuizScores to count.
   * @example
   * // Count the number of QuizScores
   * const count = await prisma.quizScore.count({
   *   where: {
   *     // ... the filter for the QuizScores we want to count
   *   }
   * })
  **/
  count<T extends QuizScoreCountArgs>(
    args?: Prisma.Subset<T, QuizScoreCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuizScoreCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuizScore.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizScoreAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuizScoreAggregateArgs>(args: Prisma.Subset<T, QuizScoreAggregateArgs>): Prisma.PrismaPromise<GetQuizScoreAggregateType<T>>

  /**
   * Group by QuizScore.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizScoreGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuizScoreGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuizScoreGroupByArgs['orderBy'] }
      : { orderBy?: QuizScoreGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuizScoreGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuizScoreGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuizScore model
 */
readonly fields: QuizScoreFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuizScore.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuizScoreClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuizScore model
 */
export interface QuizScoreFieldRefs {
  readonly id: Prisma.FieldRef<"QuizScore", 'String'>
  readonly userId: Prisma.FieldRef<"QuizScore", 'String'>
  readonly score: Prisma.FieldRef<"QuizScore", 'Int'>
  readonly totalQuestions: Prisma.FieldRef<"QuizScore", 'Int'>
  readonly createdAt: Prisma.FieldRef<"QuizScore", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QuizScore findUnique
 */
export type QuizScoreFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizScore
   */
  select?: Prisma.QuizScoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizScore
   */
  omit?: Prisma.QuizScoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizScoreInclude<ExtArgs> | null
  /**
   * Filter, which QuizScore to fetch.
   */
  where: Prisma.QuizScoreWhereUniqueInput
}

/**
 * QuizScore findUniqueOrThrow
 */
export type QuizScoreFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizScore
   */
  select?: Prisma.QuizScoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizScore
   */
  omit?: Prisma.QuizScoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizScoreInclude<ExtArgs> | null
  /**
   * Filter, which QuizScore to fetch.
   */
  where: Prisma.QuizScoreWhereUniqueInput
}

/**
 * QuizScore findFirst
 */
export type QuizScoreFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizScore
   */
  select?: Prisma.QuizScoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizScore
   */
  omit?: Prisma.QuizScoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizScoreInclude<ExtArgs> | null
  /**
   * Filter, which QuizScore to fetch.
   */
  where?: Prisma.QuizScoreWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizScores to fetch.
   */
  orderBy?: Prisma.QuizScoreOrderByWithRelationInput | Prisma.QuizScoreOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizScores.
   */
  cursor?: Prisma.QuizScoreWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizScores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizScores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizScores.
   */
  distinct?: Prisma.QuizScoreScalarFieldEnum | Prisma.QuizScoreScalarFieldEnum[]
}

/**
 * QuizScore findFirstOrThrow
 */
export type QuizScoreFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizScore
   */
  select?: Prisma.QuizScoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizScore
   */
  omit?: Prisma.QuizScoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizScoreInclude<ExtArgs> | null
  /**
   * Filter, which QuizScore to fetch.
   */
  where?: Prisma.QuizScoreWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizScores to fetch.
   */
  orderBy?: Prisma.QuizScoreOrderByWithRelationInput | Prisma.QuizScoreOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizScores.
   */
  cursor?: Prisma.QuizScoreWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizScores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizScores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizScores.
   */
  distinct?: Prisma.QuizScoreScalarFieldEnum | Prisma.QuizScoreScalarFieldEnum[]
}

/**
 * QuizScore findMany
 */
export type QuizScoreFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizScore
   */
  select?: Prisma.QuizScoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizScore
   */
  omit?: Prisma.QuizScoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizScoreInclude<ExtArgs> | null
  /**
   * Filter, which QuizScores to fetch.
   */
  where?: Prisma.QuizScoreWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizScores to fetch.
   */
  orderBy?: Prisma.QuizScoreOrderByWithRelationInput | Prisma.QuizScoreOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuizScores.
   */
  cursor?: Prisma.QuizScoreWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizScores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizScores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizScores.
   */
  distinct?: Prisma.QuizScoreScalarFieldEnum | Prisma.QuizScoreScalarFieldEnum[]
}

/**
 * QuizScore create
 */
export type QuizScoreCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizScore
   */
  select?: Prisma.QuizScoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizScore
   */
  omit?: Prisma.QuizScoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizScoreInclude<ExtArgs> | null
  /**
   * The data needed to create a QuizScore.
   */
  data: Prisma.XOR<Prisma.QuizScoreCreateInput, Prisma.QuizScoreUncheckedCreateInput>
}

/**
 * QuizScore createMany
 */
export type QuizScoreCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuizScores.
   */
  data: Prisma.QuizScoreCreateManyInput | Prisma.QuizScoreCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QuizScore createManyAndReturn
 */
export type QuizScoreCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizScore
   */
  select?: Prisma.QuizScoreSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizScore
   */
  omit?: Prisma.QuizScoreOmit<ExtArgs> | null
  /**
   * The data used to create many QuizScores.
   */
  data: Prisma.QuizScoreCreateManyInput | Prisma.QuizScoreCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizScoreIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuizScore update
 */
export type QuizScoreUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizScore
   */
  select?: Prisma.QuizScoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizScore
   */
  omit?: Prisma.QuizScoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizScoreInclude<ExtArgs> | null
  /**
   * The data needed to update a QuizScore.
   */
  data: Prisma.XOR<Prisma.QuizScoreUpdateInput, Prisma.QuizScoreUncheckedUpdateInput>
  /**
   * Choose, which QuizScore to update.
   */
  where: Prisma.QuizScoreWhereUniqueInput
}

/**
 * QuizScore updateMany
 */
export type QuizScoreUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuizScores.
   */
  data: Prisma.XOR<Prisma.QuizScoreUpdateManyMutationInput, Prisma.QuizScoreUncheckedUpdateManyInput>
  /**
   * Filter which QuizScores to update
   */
  where?: Prisma.QuizScoreWhereInput
  /**
   * Limit how many QuizScores to update.
   */
  limit?: number
}

/**
 * QuizScore updateManyAndReturn
 */
export type QuizScoreUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizScore
   */
  select?: Prisma.QuizScoreSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizScore
   */
  omit?: Prisma.QuizScoreOmit<ExtArgs> | null
  /**
   * The data used to update QuizScores.
   */
  data: Prisma.XOR<Prisma.QuizScoreUpdateManyMutationInput, Prisma.QuizScoreUncheckedUpdateManyInput>
  /**
   * Filter which QuizScores to update
   */
  where?: Prisma.QuizScoreWhereInput
  /**
   * Limit how many QuizScores to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizScoreIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuizScore upsert
 */
export type QuizScoreUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizScore
   */
  select?: Prisma.QuizScoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizScore
   */
  omit?: Prisma.QuizScoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizScoreInclude<ExtArgs> | null
  /**
   * The filter to search for the QuizScore to update in case it exists.
   */
  where: Prisma.QuizScoreWhereUniqueInput
  /**
   * In case the QuizScore found by the `where` argument doesn't exist, create a new QuizScore with this data.
   */
  create: Prisma.XOR<Prisma.QuizScoreCreateInput, Prisma.QuizScoreUncheckedCreateInput>
  /**
   * In case the QuizScore was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuizScoreUpdateInput, Prisma.QuizScoreUncheckedUpdateInput>
}

/**
 * QuizScore delete
 */
export type QuizScoreDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizScore
   */
  select?: Prisma.QuizScoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizScore
   */
  omit?: Prisma.QuizScoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizScoreInclude<ExtArgs> | null
  /**
   * Filter which QuizScore to delete.
   */
  where: Prisma.QuizScoreWhereUniqueInput
}

/**
 * QuizScore deleteMany
 */
export type QuizScoreDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizScores to delete
   */
  where?: Prisma.QuizScoreWhereInput
  /**
   * Limit how many QuizScores to delete.
   */
  limit?: number
}

/**
 * QuizScore without action
 */
export type QuizScoreDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizScore
   */
  select?: Prisma.QuizScoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizScore
   */
  omit?: Prisma.QuizScoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizScoreInclude<ExtArgs> | null
}
