
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TaxArticle` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TaxArticle
 * 
 */
export type TaxArticleModel = runtime.Types.Result.DefaultSelection<Prisma.$TaxArticlePayload>

export type AggregateTaxArticle = {
  _count: TaxArticleCountAggregateOutputType | null
  _min: TaxArticleMinAggregateOutputType | null
  _max: TaxArticleMaxAggregateOutputType | null
}

export type TaxArticleMinAggregateOutputType = {
  id: string | null
  title: string | null
  summary: string | null
  content: string | null
  source: string | null
  url: string | null
  isFeatured: boolean | null
  createdAt: Date | null
}

export type TaxArticleMaxAggregateOutputType = {
  id: string | null
  title: string | null
  summary: string | null
  content: string | null
  source: string | null
  url: string | null
  isFeatured: boolean | null
  createdAt: Date | null
}

export type TaxArticleCountAggregateOutputType = {
  id: number
  title: number
  summary: number
  content: number
  source: number
  url: number
  isFeatured: number
  createdAt: number
  _all: number
}


export type TaxArticleMinAggregateInputType = {
  id?: true
  title?: true
  summary?: true
  content?: true
  source?: true
  url?: true
  isFeatured?: true
  createdAt?: true
}

export type TaxArticleMaxAggregateInputType = {
  id?: true
  title?: true
  summary?: true
  content?: true
  source?: true
  url?: true
  isFeatured?: true
  createdAt?: true
}

export type TaxArticleCountAggregateInputType = {
  id?: true
  title?: true
  summary?: true
  content?: true
  source?: true
  url?: true
  isFeatured?: true
  createdAt?: true
  _all?: true
}

export type TaxArticleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaxArticle to aggregate.
   */
  where?: Prisma.TaxArticleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxArticles to fetch.
   */
  orderBy?: Prisma.TaxArticleOrderByWithRelationInput | Prisma.TaxArticleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TaxArticleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxArticles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxArticles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TaxArticles
  **/
  _count?: true | TaxArticleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TaxArticleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TaxArticleMaxAggregateInputType
}

export type GetTaxArticleAggregateType<T extends TaxArticleAggregateArgs> = {
      [P in keyof T & keyof AggregateTaxArticle]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTaxArticle[P]>
    : Prisma.GetScalarType<T[P], AggregateTaxArticle[P]>
}




export type TaxArticleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaxArticleWhereInput
  orderBy?: Prisma.TaxArticleOrderByWithAggregationInput | Prisma.TaxArticleOrderByWithAggregationInput[]
  by: Prisma.TaxArticleScalarFieldEnum[] | Prisma.TaxArticleScalarFieldEnum
  having?: Prisma.TaxArticleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TaxArticleCountAggregateInputType | true
  _min?: TaxArticleMinAggregateInputType
  _max?: TaxArticleMaxAggregateInputType
}

export type TaxArticleGroupByOutputType = {
  id: string
  title: string
  summary: string
  content: string
  source: string
  url: string | null
  isFeatured: boolean
  createdAt: Date
  _count: TaxArticleCountAggregateOutputType | null
  _min: TaxArticleMinAggregateOutputType | null
  _max: TaxArticleMaxAggregateOutputType | null
}

export type GetTaxArticleGroupByPayload<T extends TaxArticleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TaxArticleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TaxArticleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TaxArticleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TaxArticleGroupByOutputType[P]>
      }
    >
  >



export type TaxArticleWhereInput = {
  AND?: Prisma.TaxArticleWhereInput | Prisma.TaxArticleWhereInput[]
  OR?: Prisma.TaxArticleWhereInput[]
  NOT?: Prisma.TaxArticleWhereInput | Prisma.TaxArticleWhereInput[]
  id?: Prisma.StringFilter<"TaxArticle"> | string
  title?: Prisma.StringFilter<"TaxArticle"> | string
  summary?: Prisma.StringFilter<"TaxArticle"> | string
  content?: Prisma.StringFilter<"TaxArticle"> | string
  source?: Prisma.StringFilter<"TaxArticle"> | string
  url?: Prisma.StringNullableFilter<"TaxArticle"> | string | null
  isFeatured?: Prisma.BoolFilter<"TaxArticle"> | boolean
  createdAt?: Prisma.DateTimeFilter<"TaxArticle"> | Date | string
}

export type TaxArticleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  content?: Prisma.SortOrder
  source?: Prisma.SortOrder
  url?: Prisma.SortOrderInput | Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TaxArticleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TaxArticleWhereInput | Prisma.TaxArticleWhereInput[]
  OR?: Prisma.TaxArticleWhereInput[]
  NOT?: Prisma.TaxArticleWhereInput | Prisma.TaxArticleWhereInput[]
  title?: Prisma.StringFilter<"TaxArticle"> | string
  summary?: Prisma.StringFilter<"TaxArticle"> | string
  content?: Prisma.StringFilter<"TaxArticle"> | string
  source?: Prisma.StringFilter<"TaxArticle"> | string
  url?: Prisma.StringNullableFilter<"TaxArticle"> | string | null
  isFeatured?: Prisma.BoolFilter<"TaxArticle"> | boolean
  createdAt?: Prisma.DateTimeFilter<"TaxArticle"> | Date | string
}, "id">

export type TaxArticleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  content?: Prisma.SortOrder
  source?: Prisma.SortOrder
  url?: Prisma.SortOrderInput | Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.TaxArticleCountOrderByAggregateInput
  _max?: Prisma.TaxArticleMaxOrderByAggregateInput
  _min?: Prisma.TaxArticleMinOrderByAggregateInput
}

export type TaxArticleScalarWhereWithAggregatesInput = {
  AND?: Prisma.TaxArticleScalarWhereWithAggregatesInput | Prisma.TaxArticleScalarWhereWithAggregatesInput[]
  OR?: Prisma.TaxArticleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TaxArticleScalarWhereWithAggregatesInput | Prisma.TaxArticleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TaxArticle"> | string
  title?: Prisma.StringWithAggregatesFilter<"TaxArticle"> | string
  summary?: Prisma.StringWithAggregatesFilter<"TaxArticle"> | string
  content?: Prisma.StringWithAggregatesFilter<"TaxArticle"> | string
  source?: Prisma.StringWithAggregatesFilter<"TaxArticle"> | string
  url?: Prisma.StringNullableWithAggregatesFilter<"TaxArticle"> | string | null
  isFeatured?: Prisma.BoolWithAggregatesFilter<"TaxArticle"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TaxArticle"> | Date | string
}

export type TaxArticleCreateInput = {
  id?: string
  title: string
  summary: string
  content: string
  source: string
  url?: string | null
  isFeatured?: boolean
  createdAt?: Date | string
}

export type TaxArticleUncheckedCreateInput = {
  id?: string
  title: string
  summary: string
  content: string
  source: string
  url?: string | null
  isFeatured?: boolean
  createdAt?: Date | string
}

export type TaxArticleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaxArticleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaxArticleCreateManyInput = {
  id?: string
  title: string
  summary: string
  content: string
  source: string
  url?: string | null
  isFeatured?: boolean
  createdAt?: Date | string
}

export type TaxArticleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaxArticleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaxArticleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  content?: Prisma.SortOrder
  source?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TaxArticleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  content?: Prisma.SortOrder
  source?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TaxArticleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  content?: Prisma.SortOrder
  source?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}



export type TaxArticleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  summary?: boolean
  content?: boolean
  source?: boolean
  url?: boolean
  isFeatured?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["taxArticle"]>

export type TaxArticleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  summary?: boolean
  content?: boolean
  source?: boolean
  url?: boolean
  isFeatured?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["taxArticle"]>

export type TaxArticleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  summary?: boolean
  content?: boolean
  source?: boolean
  url?: boolean
  isFeatured?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["taxArticle"]>

export type TaxArticleSelectScalar = {
  id?: boolean
  title?: boolean
  summary?: boolean
  content?: boolean
  source?: boolean
  url?: boolean
  isFeatured?: boolean
  createdAt?: boolean
}

export type TaxArticleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "summary" | "content" | "source" | "url" | "isFeatured" | "createdAt", ExtArgs["result"]["taxArticle"]>

export type $TaxArticlePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TaxArticle"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    summary: string
    content: string
    source: string
    url: string | null
    isFeatured: boolean
    createdAt: Date
  }, ExtArgs["result"]["taxArticle"]>
  composites: {}
}

export type TaxArticleGetPayload<S extends boolean | null | undefined | TaxArticleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TaxArticlePayload, S>

export type TaxArticleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TaxArticleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TaxArticleCountAggregateInputType | true
  }

export interface TaxArticleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TaxArticle'], meta: { name: 'TaxArticle' } }
  /**
   * Find zero or one TaxArticle that matches the filter.
   * @param {TaxArticleFindUniqueArgs} args - Arguments to find a TaxArticle
   * @example
   * // Get one TaxArticle
   * const taxArticle = await prisma.taxArticle.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TaxArticleFindUniqueArgs>(args: Prisma.SelectSubset<T, TaxArticleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TaxArticleClient<runtime.Types.Result.GetResult<Prisma.$TaxArticlePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TaxArticle that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TaxArticleFindUniqueOrThrowArgs} args - Arguments to find a TaxArticle
   * @example
   * // Get one TaxArticle
   * const taxArticle = await prisma.taxArticle.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TaxArticleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TaxArticleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaxArticleClient<runtime.Types.Result.GetResult<Prisma.$TaxArticlePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaxArticle that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxArticleFindFirstArgs} args - Arguments to find a TaxArticle
   * @example
   * // Get one TaxArticle
   * const taxArticle = await prisma.taxArticle.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TaxArticleFindFirstArgs>(args?: Prisma.SelectSubset<T, TaxArticleFindFirstArgs<ExtArgs>>): Prisma.Prisma__TaxArticleClient<runtime.Types.Result.GetResult<Prisma.$TaxArticlePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaxArticle that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxArticleFindFirstOrThrowArgs} args - Arguments to find a TaxArticle
   * @example
   * // Get one TaxArticle
   * const taxArticle = await prisma.taxArticle.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TaxArticleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TaxArticleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaxArticleClient<runtime.Types.Result.GetResult<Prisma.$TaxArticlePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TaxArticles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxArticleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TaxArticles
   * const taxArticles = await prisma.taxArticle.findMany()
   * 
   * // Get first 10 TaxArticles
   * const taxArticles = await prisma.taxArticle.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const taxArticleWithIdOnly = await prisma.taxArticle.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TaxArticleFindManyArgs>(args?: Prisma.SelectSubset<T, TaxArticleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaxArticlePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TaxArticle.
   * @param {TaxArticleCreateArgs} args - Arguments to create a TaxArticle.
   * @example
   * // Create one TaxArticle
   * const TaxArticle = await prisma.taxArticle.create({
   *   data: {
   *     // ... data to create a TaxArticle
   *   }
   * })
   * 
   */
  create<T extends TaxArticleCreateArgs>(args: Prisma.SelectSubset<T, TaxArticleCreateArgs<ExtArgs>>): Prisma.Prisma__TaxArticleClient<runtime.Types.Result.GetResult<Prisma.$TaxArticlePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TaxArticles.
   * @param {TaxArticleCreateManyArgs} args - Arguments to create many TaxArticles.
   * @example
   * // Create many TaxArticles
   * const taxArticle = await prisma.taxArticle.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TaxArticleCreateManyArgs>(args?: Prisma.SelectSubset<T, TaxArticleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TaxArticles and returns the data saved in the database.
   * @param {TaxArticleCreateManyAndReturnArgs} args - Arguments to create many TaxArticles.
   * @example
   * // Create many TaxArticles
   * const taxArticle = await prisma.taxArticle.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TaxArticles and only return the `id`
   * const taxArticleWithIdOnly = await prisma.taxArticle.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TaxArticleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TaxArticleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaxArticlePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TaxArticle.
   * @param {TaxArticleDeleteArgs} args - Arguments to delete one TaxArticle.
   * @example
   * // Delete one TaxArticle
   * const TaxArticle = await prisma.taxArticle.delete({
   *   where: {
   *     // ... filter to delete one TaxArticle
   *   }
   * })
   * 
   */
  delete<T extends TaxArticleDeleteArgs>(args: Prisma.SelectSubset<T, TaxArticleDeleteArgs<ExtArgs>>): Prisma.Prisma__TaxArticleClient<runtime.Types.Result.GetResult<Prisma.$TaxArticlePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TaxArticle.
   * @param {TaxArticleUpdateArgs} args - Arguments to update one TaxArticle.
   * @example
   * // Update one TaxArticle
   * const taxArticle = await prisma.taxArticle.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TaxArticleUpdateArgs>(args: Prisma.SelectSubset<T, TaxArticleUpdateArgs<ExtArgs>>): Prisma.Prisma__TaxArticleClient<runtime.Types.Result.GetResult<Prisma.$TaxArticlePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TaxArticles.
   * @param {TaxArticleDeleteManyArgs} args - Arguments to filter TaxArticles to delete.
   * @example
   * // Delete a few TaxArticles
   * const { count } = await prisma.taxArticle.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TaxArticleDeleteManyArgs>(args?: Prisma.SelectSubset<T, TaxArticleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaxArticles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxArticleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TaxArticles
   * const taxArticle = await prisma.taxArticle.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TaxArticleUpdateManyArgs>(args: Prisma.SelectSubset<T, TaxArticleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaxArticles and returns the data updated in the database.
   * @param {TaxArticleUpdateManyAndReturnArgs} args - Arguments to update many TaxArticles.
   * @example
   * // Update many TaxArticles
   * const taxArticle = await prisma.taxArticle.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TaxArticles and only return the `id`
   * const taxArticleWithIdOnly = await prisma.taxArticle.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TaxArticleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TaxArticleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaxArticlePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TaxArticle.
   * @param {TaxArticleUpsertArgs} args - Arguments to update or create a TaxArticle.
   * @example
   * // Update or create a TaxArticle
   * const taxArticle = await prisma.taxArticle.upsert({
   *   create: {
   *     // ... data to create a TaxArticle
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TaxArticle we want to update
   *   }
   * })
   */
  upsert<T extends TaxArticleUpsertArgs>(args: Prisma.SelectSubset<T, TaxArticleUpsertArgs<ExtArgs>>): Prisma.Prisma__TaxArticleClient<runtime.Types.Result.GetResult<Prisma.$TaxArticlePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TaxArticles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxArticleCountArgs} args - Arguments to filter TaxArticles to count.
   * @example
   * // Count the number of TaxArticles
   * const count = await prisma.taxArticle.count({
   *   where: {
   *     // ... the filter for the TaxArticles we want to count
   *   }
   * })
  **/
  count<T extends TaxArticleCountArgs>(
    args?: Prisma.Subset<T, TaxArticleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TaxArticleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TaxArticle.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxArticleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TaxArticleAggregateArgs>(args: Prisma.Subset<T, TaxArticleAggregateArgs>): Prisma.PrismaPromise<GetTaxArticleAggregateType<T>>

  /**
   * Group by TaxArticle.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxArticleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TaxArticleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TaxArticleGroupByArgs['orderBy'] }
      : { orderBy?: TaxArticleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TaxArticleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTaxArticleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TaxArticle model
 */
readonly fields: TaxArticleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TaxArticle.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TaxArticleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TaxArticle model
 */
export interface TaxArticleFieldRefs {
  readonly id: Prisma.FieldRef<"TaxArticle", 'String'>
  readonly title: Prisma.FieldRef<"TaxArticle", 'String'>
  readonly summary: Prisma.FieldRef<"TaxArticle", 'String'>
  readonly content: Prisma.FieldRef<"TaxArticle", 'String'>
  readonly source: Prisma.FieldRef<"TaxArticle", 'String'>
  readonly url: Prisma.FieldRef<"TaxArticle", 'String'>
  readonly isFeatured: Prisma.FieldRef<"TaxArticle", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"TaxArticle", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TaxArticle findUnique
 */
export type TaxArticleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxArticle
   */
  select?: Prisma.TaxArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxArticle
   */
  omit?: Prisma.TaxArticleOmit<ExtArgs> | null
  /**
   * Filter, which TaxArticle to fetch.
   */
  where: Prisma.TaxArticleWhereUniqueInput
}

/**
 * TaxArticle findUniqueOrThrow
 */
export type TaxArticleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxArticle
   */
  select?: Prisma.TaxArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxArticle
   */
  omit?: Prisma.TaxArticleOmit<ExtArgs> | null
  /**
   * Filter, which TaxArticle to fetch.
   */
  where: Prisma.TaxArticleWhereUniqueInput
}

/**
 * TaxArticle findFirst
 */
export type TaxArticleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxArticle
   */
  select?: Prisma.TaxArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxArticle
   */
  omit?: Prisma.TaxArticleOmit<ExtArgs> | null
  /**
   * Filter, which TaxArticle to fetch.
   */
  where?: Prisma.TaxArticleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxArticles to fetch.
   */
  orderBy?: Prisma.TaxArticleOrderByWithRelationInput | Prisma.TaxArticleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaxArticles.
   */
  cursor?: Prisma.TaxArticleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxArticles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxArticles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaxArticles.
   */
  distinct?: Prisma.TaxArticleScalarFieldEnum | Prisma.TaxArticleScalarFieldEnum[]
}

/**
 * TaxArticle findFirstOrThrow
 */
export type TaxArticleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxArticle
   */
  select?: Prisma.TaxArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxArticle
   */
  omit?: Prisma.TaxArticleOmit<ExtArgs> | null
  /**
   * Filter, which TaxArticle to fetch.
   */
  where?: Prisma.TaxArticleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxArticles to fetch.
   */
  orderBy?: Prisma.TaxArticleOrderByWithRelationInput | Prisma.TaxArticleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaxArticles.
   */
  cursor?: Prisma.TaxArticleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxArticles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxArticles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaxArticles.
   */
  distinct?: Prisma.TaxArticleScalarFieldEnum | Prisma.TaxArticleScalarFieldEnum[]
}

/**
 * TaxArticle findMany
 */
export type TaxArticleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxArticle
   */
  select?: Prisma.TaxArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxArticle
   */
  omit?: Prisma.TaxArticleOmit<ExtArgs> | null
  /**
   * Filter, which TaxArticles to fetch.
   */
  where?: Prisma.TaxArticleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxArticles to fetch.
   */
  orderBy?: Prisma.TaxArticleOrderByWithRelationInput | Prisma.TaxArticleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TaxArticles.
   */
  cursor?: Prisma.TaxArticleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxArticles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxArticles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaxArticles.
   */
  distinct?: Prisma.TaxArticleScalarFieldEnum | Prisma.TaxArticleScalarFieldEnum[]
}

/**
 * TaxArticle create
 */
export type TaxArticleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxArticle
   */
  select?: Prisma.TaxArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxArticle
   */
  omit?: Prisma.TaxArticleOmit<ExtArgs> | null
  /**
   * The data needed to create a TaxArticle.
   */
  data: Prisma.XOR<Prisma.TaxArticleCreateInput, Prisma.TaxArticleUncheckedCreateInput>
}

/**
 * TaxArticle createMany
 */
export type TaxArticleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TaxArticles.
   */
  data: Prisma.TaxArticleCreateManyInput | Prisma.TaxArticleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TaxArticle createManyAndReturn
 */
export type TaxArticleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxArticle
   */
  select?: Prisma.TaxArticleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaxArticle
   */
  omit?: Prisma.TaxArticleOmit<ExtArgs> | null
  /**
   * The data used to create many TaxArticles.
   */
  data: Prisma.TaxArticleCreateManyInput | Prisma.TaxArticleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TaxArticle update
 */
export type TaxArticleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxArticle
   */
  select?: Prisma.TaxArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxArticle
   */
  omit?: Prisma.TaxArticleOmit<ExtArgs> | null
  /**
   * The data needed to update a TaxArticle.
   */
  data: Prisma.XOR<Prisma.TaxArticleUpdateInput, Prisma.TaxArticleUncheckedUpdateInput>
  /**
   * Choose, which TaxArticle to update.
   */
  where: Prisma.TaxArticleWhereUniqueInput
}

/**
 * TaxArticle updateMany
 */
export type TaxArticleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TaxArticles.
   */
  data: Prisma.XOR<Prisma.TaxArticleUpdateManyMutationInput, Prisma.TaxArticleUncheckedUpdateManyInput>
  /**
   * Filter which TaxArticles to update
   */
  where?: Prisma.TaxArticleWhereInput
  /**
   * Limit how many TaxArticles to update.
   */
  limit?: number
}

/**
 * TaxArticle updateManyAndReturn
 */
export type TaxArticleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxArticle
   */
  select?: Prisma.TaxArticleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaxArticle
   */
  omit?: Prisma.TaxArticleOmit<ExtArgs> | null
  /**
   * The data used to update TaxArticles.
   */
  data: Prisma.XOR<Prisma.TaxArticleUpdateManyMutationInput, Prisma.TaxArticleUncheckedUpdateManyInput>
  /**
   * Filter which TaxArticles to update
   */
  where?: Prisma.TaxArticleWhereInput
  /**
   * Limit how many TaxArticles to update.
   */
  limit?: number
}

/**
 * TaxArticle upsert
 */
export type TaxArticleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxArticle
   */
  select?: Prisma.TaxArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxArticle
   */
  omit?: Prisma.TaxArticleOmit<ExtArgs> | null
  /**
   * The filter to search for the TaxArticle to update in case it exists.
   */
  where: Prisma.TaxArticleWhereUniqueInput
  /**
   * In case the TaxArticle found by the `where` argument doesn't exist, create a new TaxArticle with this data.
   */
  create: Prisma.XOR<Prisma.TaxArticleCreateInput, Prisma.TaxArticleUncheckedCreateInput>
  /**
   * In case the TaxArticle was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TaxArticleUpdateInput, Prisma.TaxArticleUncheckedUpdateInput>
}

/**
 * TaxArticle delete
 */
export type TaxArticleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxArticle
   */
  select?: Prisma.TaxArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxArticle
   */
  omit?: Prisma.TaxArticleOmit<ExtArgs> | null
  /**
   * Filter which TaxArticle to delete.
   */
  where: Prisma.TaxArticleWhereUniqueInput
}

/**
 * TaxArticle deleteMany
 */
export type TaxArticleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaxArticles to delete
   */
  where?: Prisma.TaxArticleWhereInput
  /**
   * Limit how many TaxArticles to delete.
   */
  limit?: number
}

/**
 * TaxArticle without action
 */
export type TaxArticleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxArticle
   */
  select?: Prisma.TaxArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxArticle
   */
  omit?: Prisma.TaxArticleOmit<ExtArgs> | null
}
