
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TaxProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TaxProfile
 * 
 */
export type TaxProfileModel = runtime.Types.Result.DefaultSelection<Prisma.$TaxProfilePayload>

export type AggregateTaxProfile = {
  _count: TaxProfileCountAggregateOutputType | null
  _avg: TaxProfileAvgAggregateOutputType | null
  _sum: TaxProfileSumAggregateOutputType | null
  _min: TaxProfileMinAggregateOutputType | null
  _max: TaxProfileMaxAggregateOutputType | null
}

export type TaxProfileAvgAggregateOutputType = {
  monthlyIncome: runtime.Decimal | null
  annualGross: runtime.Decimal | null
  rentPaid: runtime.Decimal | null
  pensionRate: runtime.Decimal | null
  computedTax: runtime.Decimal | null
  netIncome: runtime.Decimal | null
}

export type TaxProfileSumAggregateOutputType = {
  monthlyIncome: runtime.Decimal | null
  annualGross: runtime.Decimal | null
  rentPaid: runtime.Decimal | null
  pensionRate: runtime.Decimal | null
  computedTax: runtime.Decimal | null
  netIncome: runtime.Decimal | null
}

export type TaxProfileMinAggregateOutputType = {
  id: string | null
  userId: string | null
  monthlyIncome: runtime.Decimal | null
  annualGross: runtime.Decimal | null
  rentPaid: runtime.Decimal | null
  pensionRate: runtime.Decimal | null
  computedTax: runtime.Decimal | null
  netIncome: runtime.Decimal | null
  isExempt: boolean | null
  citExemption: string | null
  createdAt: Date | null
}

export type TaxProfileMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  monthlyIncome: runtime.Decimal | null
  annualGross: runtime.Decimal | null
  rentPaid: runtime.Decimal | null
  pensionRate: runtime.Decimal | null
  computedTax: runtime.Decimal | null
  netIncome: runtime.Decimal | null
  isExempt: boolean | null
  citExemption: string | null
  createdAt: Date | null
}

export type TaxProfileCountAggregateOutputType = {
  id: number
  userId: number
  monthlyIncome: number
  annualGross: number
  rentPaid: number
  pensionRate: number
  computedTax: number
  netIncome: number
  isExempt: number
  citExemption: number
  createdAt: number
  _all: number
}


export type TaxProfileAvgAggregateInputType = {
  monthlyIncome?: true
  annualGross?: true
  rentPaid?: true
  pensionRate?: true
  computedTax?: true
  netIncome?: true
}

export type TaxProfileSumAggregateInputType = {
  monthlyIncome?: true
  annualGross?: true
  rentPaid?: true
  pensionRate?: true
  computedTax?: true
  netIncome?: true
}

export type TaxProfileMinAggregateInputType = {
  id?: true
  userId?: true
  monthlyIncome?: true
  annualGross?: true
  rentPaid?: true
  pensionRate?: true
  computedTax?: true
  netIncome?: true
  isExempt?: true
  citExemption?: true
  createdAt?: true
}

export type TaxProfileMaxAggregateInputType = {
  id?: true
  userId?: true
  monthlyIncome?: true
  annualGross?: true
  rentPaid?: true
  pensionRate?: true
  computedTax?: true
  netIncome?: true
  isExempt?: true
  citExemption?: true
  createdAt?: true
}

export type TaxProfileCountAggregateInputType = {
  id?: true
  userId?: true
  monthlyIncome?: true
  annualGross?: true
  rentPaid?: true
  pensionRate?: true
  computedTax?: true
  netIncome?: true
  isExempt?: true
  citExemption?: true
  createdAt?: true
  _all?: true
}

export type TaxProfileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaxProfile to aggregate.
   */
  where?: Prisma.TaxProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxProfiles to fetch.
   */
  orderBy?: Prisma.TaxProfileOrderByWithRelationInput | Prisma.TaxProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TaxProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TaxProfiles
  **/
  _count?: true | TaxProfileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TaxProfileAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TaxProfileSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TaxProfileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TaxProfileMaxAggregateInputType
}

export type GetTaxProfileAggregateType<T extends TaxProfileAggregateArgs> = {
      [P in keyof T & keyof AggregateTaxProfile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTaxProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateTaxProfile[P]>
}




export type TaxProfileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaxProfileWhereInput
  orderBy?: Prisma.TaxProfileOrderByWithAggregationInput | Prisma.TaxProfileOrderByWithAggregationInput[]
  by: Prisma.TaxProfileScalarFieldEnum[] | Prisma.TaxProfileScalarFieldEnum
  having?: Prisma.TaxProfileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TaxProfileCountAggregateInputType | true
  _avg?: TaxProfileAvgAggregateInputType
  _sum?: TaxProfileSumAggregateInputType
  _min?: TaxProfileMinAggregateInputType
  _max?: TaxProfileMaxAggregateInputType
}

export type TaxProfileGroupByOutputType = {
  id: string
  userId: string
  monthlyIncome: runtime.Decimal
  annualGross: runtime.Decimal
  rentPaid: runtime.Decimal
  pensionRate: runtime.Decimal
  computedTax: runtime.Decimal
  netIncome: runtime.Decimal
  isExempt: boolean
  citExemption: string
  createdAt: Date
  _count: TaxProfileCountAggregateOutputType | null
  _avg: TaxProfileAvgAggregateOutputType | null
  _sum: TaxProfileSumAggregateOutputType | null
  _min: TaxProfileMinAggregateOutputType | null
  _max: TaxProfileMaxAggregateOutputType | null
}

export type GetTaxProfileGroupByPayload<T extends TaxProfileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TaxProfileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TaxProfileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TaxProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TaxProfileGroupByOutputType[P]>
      }
    >
  >



export type TaxProfileWhereInput = {
  AND?: Prisma.TaxProfileWhereInput | Prisma.TaxProfileWhereInput[]
  OR?: Prisma.TaxProfileWhereInput[]
  NOT?: Prisma.TaxProfileWhereInput | Prisma.TaxProfileWhereInput[]
  id?: Prisma.StringFilter<"TaxProfile"> | string
  userId?: Prisma.StringFilter<"TaxProfile"> | string
  monthlyIncome?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: Prisma.BoolFilter<"TaxProfile"> | boolean
  citExemption?: Prisma.StringFilter<"TaxProfile"> | string
  createdAt?: Prisma.DateTimeFilter<"TaxProfile"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type TaxProfileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  monthlyIncome?: Prisma.SortOrder
  annualGross?: Prisma.SortOrder
  rentPaid?: Prisma.SortOrder
  pensionRate?: Prisma.SortOrder
  computedTax?: Prisma.SortOrder
  netIncome?: Prisma.SortOrder
  isExempt?: Prisma.SortOrder
  citExemption?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type TaxProfileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TaxProfileWhereInput | Prisma.TaxProfileWhereInput[]
  OR?: Prisma.TaxProfileWhereInput[]
  NOT?: Prisma.TaxProfileWhereInput | Prisma.TaxProfileWhereInput[]
  userId?: Prisma.StringFilter<"TaxProfile"> | string
  monthlyIncome?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: Prisma.BoolFilter<"TaxProfile"> | boolean
  citExemption?: Prisma.StringFilter<"TaxProfile"> | string
  createdAt?: Prisma.DateTimeFilter<"TaxProfile"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type TaxProfileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  monthlyIncome?: Prisma.SortOrder
  annualGross?: Prisma.SortOrder
  rentPaid?: Prisma.SortOrder
  pensionRate?: Prisma.SortOrder
  computedTax?: Prisma.SortOrder
  netIncome?: Prisma.SortOrder
  isExempt?: Prisma.SortOrder
  citExemption?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.TaxProfileCountOrderByAggregateInput
  _avg?: Prisma.TaxProfileAvgOrderByAggregateInput
  _max?: Prisma.TaxProfileMaxOrderByAggregateInput
  _min?: Prisma.TaxProfileMinOrderByAggregateInput
  _sum?: Prisma.TaxProfileSumOrderByAggregateInput
}

export type TaxProfileScalarWhereWithAggregatesInput = {
  AND?: Prisma.TaxProfileScalarWhereWithAggregatesInput | Prisma.TaxProfileScalarWhereWithAggregatesInput[]
  OR?: Prisma.TaxProfileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TaxProfileScalarWhereWithAggregatesInput | Prisma.TaxProfileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TaxProfile"> | string
  userId?: Prisma.StringWithAggregatesFilter<"TaxProfile"> | string
  monthlyIncome?: Prisma.DecimalWithAggregatesFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross?: Prisma.DecimalWithAggregatesFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid?: Prisma.DecimalWithAggregatesFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate?: Prisma.DecimalWithAggregatesFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax?: Prisma.DecimalWithAggregatesFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome?: Prisma.DecimalWithAggregatesFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: Prisma.BoolWithAggregatesFilter<"TaxProfile"> | boolean
  citExemption?: Prisma.StringWithAggregatesFilter<"TaxProfile"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TaxProfile"> | Date | string
}

export type TaxProfileCreateInput = {
  id?: string
  monthlyIncome: runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross: runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax: runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome: runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: boolean
  citExemption?: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTaxProfilesInput
}

export type TaxProfileUncheckedCreateInput = {
  id?: string
  userId: string
  monthlyIncome: runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross: runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax: runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome: runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: boolean
  citExemption?: string
  createdAt?: Date | string
}

export type TaxProfileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  citExemption?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTaxProfilesNestedInput
}

export type TaxProfileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  citExemption?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaxProfileCreateManyInput = {
  id?: string
  userId: string
  monthlyIncome: runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross: runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax: runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome: runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: boolean
  citExemption?: string
  createdAt?: Date | string
}

export type TaxProfileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  citExemption?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaxProfileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  citExemption?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaxProfileListRelationFilter = {
  every?: Prisma.TaxProfileWhereInput
  some?: Prisma.TaxProfileWhereInput
  none?: Prisma.TaxProfileWhereInput
}

export type TaxProfileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TaxProfileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  monthlyIncome?: Prisma.SortOrder
  annualGross?: Prisma.SortOrder
  rentPaid?: Prisma.SortOrder
  pensionRate?: Prisma.SortOrder
  computedTax?: Prisma.SortOrder
  netIncome?: Prisma.SortOrder
  isExempt?: Prisma.SortOrder
  citExemption?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TaxProfileAvgOrderByAggregateInput = {
  monthlyIncome?: Prisma.SortOrder
  annualGross?: Prisma.SortOrder
  rentPaid?: Prisma.SortOrder
  pensionRate?: Prisma.SortOrder
  computedTax?: Prisma.SortOrder
  netIncome?: Prisma.SortOrder
}

export type TaxProfileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  monthlyIncome?: Prisma.SortOrder
  annualGross?: Prisma.SortOrder
  rentPaid?: Prisma.SortOrder
  pensionRate?: Prisma.SortOrder
  computedTax?: Prisma.SortOrder
  netIncome?: Prisma.SortOrder
  isExempt?: Prisma.SortOrder
  citExemption?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TaxProfileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  monthlyIncome?: Prisma.SortOrder
  annualGross?: Prisma.SortOrder
  rentPaid?: Prisma.SortOrder
  pensionRate?: Prisma.SortOrder
  computedTax?: Prisma.SortOrder
  netIncome?: Prisma.SortOrder
  isExempt?: Prisma.SortOrder
  citExemption?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TaxProfileSumOrderByAggregateInput = {
  monthlyIncome?: Prisma.SortOrder
  annualGross?: Prisma.SortOrder
  rentPaid?: Prisma.SortOrder
  pensionRate?: Prisma.SortOrder
  computedTax?: Prisma.SortOrder
  netIncome?: Prisma.SortOrder
}

export type TaxProfileCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TaxProfileCreateWithoutUserInput, Prisma.TaxProfileUncheckedCreateWithoutUserInput> | Prisma.TaxProfileCreateWithoutUserInput[] | Prisma.TaxProfileUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TaxProfileCreateOrConnectWithoutUserInput | Prisma.TaxProfileCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TaxProfileCreateManyUserInputEnvelope
  connect?: Prisma.TaxProfileWhereUniqueInput | Prisma.TaxProfileWhereUniqueInput[]
}

export type TaxProfileUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TaxProfileCreateWithoutUserInput, Prisma.TaxProfileUncheckedCreateWithoutUserInput> | Prisma.TaxProfileCreateWithoutUserInput[] | Prisma.TaxProfileUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TaxProfileCreateOrConnectWithoutUserInput | Prisma.TaxProfileCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TaxProfileCreateManyUserInputEnvelope
  connect?: Prisma.TaxProfileWhereUniqueInput | Prisma.TaxProfileWhereUniqueInput[]
}

export type TaxProfileUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TaxProfileCreateWithoutUserInput, Prisma.TaxProfileUncheckedCreateWithoutUserInput> | Prisma.TaxProfileCreateWithoutUserInput[] | Prisma.TaxProfileUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TaxProfileCreateOrConnectWithoutUserInput | Prisma.TaxProfileCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TaxProfileUpsertWithWhereUniqueWithoutUserInput | Prisma.TaxProfileUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TaxProfileCreateManyUserInputEnvelope
  set?: Prisma.TaxProfileWhereUniqueInput | Prisma.TaxProfileWhereUniqueInput[]
  disconnect?: Prisma.TaxProfileWhereUniqueInput | Prisma.TaxProfileWhereUniqueInput[]
  delete?: Prisma.TaxProfileWhereUniqueInput | Prisma.TaxProfileWhereUniqueInput[]
  connect?: Prisma.TaxProfileWhereUniqueInput | Prisma.TaxProfileWhereUniqueInput[]
  update?: Prisma.TaxProfileUpdateWithWhereUniqueWithoutUserInput | Prisma.TaxProfileUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TaxProfileUpdateManyWithWhereWithoutUserInput | Prisma.TaxProfileUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TaxProfileScalarWhereInput | Prisma.TaxProfileScalarWhereInput[]
}

export type TaxProfileUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TaxProfileCreateWithoutUserInput, Prisma.TaxProfileUncheckedCreateWithoutUserInput> | Prisma.TaxProfileCreateWithoutUserInput[] | Prisma.TaxProfileUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TaxProfileCreateOrConnectWithoutUserInput | Prisma.TaxProfileCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TaxProfileUpsertWithWhereUniqueWithoutUserInput | Prisma.TaxProfileUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TaxProfileCreateManyUserInputEnvelope
  set?: Prisma.TaxProfileWhereUniqueInput | Prisma.TaxProfileWhereUniqueInput[]
  disconnect?: Prisma.TaxProfileWhereUniqueInput | Prisma.TaxProfileWhereUniqueInput[]
  delete?: Prisma.TaxProfileWhereUniqueInput | Prisma.TaxProfileWhereUniqueInput[]
  connect?: Prisma.TaxProfileWhereUniqueInput | Prisma.TaxProfileWhereUniqueInput[]
  update?: Prisma.TaxProfileUpdateWithWhereUniqueWithoutUserInput | Prisma.TaxProfileUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TaxProfileUpdateManyWithWhereWithoutUserInput | Prisma.TaxProfileUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TaxProfileScalarWhereInput | Prisma.TaxProfileScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type TaxProfileCreateWithoutUserInput = {
  id?: string
  monthlyIncome: runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross: runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax: runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome: runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: boolean
  citExemption?: string
  createdAt?: Date | string
}

export type TaxProfileUncheckedCreateWithoutUserInput = {
  id?: string
  monthlyIncome: runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross: runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax: runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome: runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: boolean
  citExemption?: string
  createdAt?: Date | string
}

export type TaxProfileCreateOrConnectWithoutUserInput = {
  where: Prisma.TaxProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.TaxProfileCreateWithoutUserInput, Prisma.TaxProfileUncheckedCreateWithoutUserInput>
}

export type TaxProfileCreateManyUserInputEnvelope = {
  data: Prisma.TaxProfileCreateManyUserInput | Prisma.TaxProfileCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type TaxProfileUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TaxProfileWhereUniqueInput
  update: Prisma.XOR<Prisma.TaxProfileUpdateWithoutUserInput, Prisma.TaxProfileUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TaxProfileCreateWithoutUserInput, Prisma.TaxProfileUncheckedCreateWithoutUserInput>
}

export type TaxProfileUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TaxProfileWhereUniqueInput
  data: Prisma.XOR<Prisma.TaxProfileUpdateWithoutUserInput, Prisma.TaxProfileUncheckedUpdateWithoutUserInput>
}

export type TaxProfileUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TaxProfileScalarWhereInput
  data: Prisma.XOR<Prisma.TaxProfileUpdateManyMutationInput, Prisma.TaxProfileUncheckedUpdateManyWithoutUserInput>
}

export type TaxProfileScalarWhereInput = {
  AND?: Prisma.TaxProfileScalarWhereInput | Prisma.TaxProfileScalarWhereInput[]
  OR?: Prisma.TaxProfileScalarWhereInput[]
  NOT?: Prisma.TaxProfileScalarWhereInput | Prisma.TaxProfileScalarWhereInput[]
  id?: Prisma.StringFilter<"TaxProfile"> | string
  userId?: Prisma.StringFilter<"TaxProfile"> | string
  monthlyIncome?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome?: Prisma.DecimalFilter<"TaxProfile"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: Prisma.BoolFilter<"TaxProfile"> | boolean
  citExemption?: Prisma.StringFilter<"TaxProfile"> | string
  createdAt?: Prisma.DateTimeFilter<"TaxProfile"> | Date | string
}

export type TaxProfileCreateManyUserInput = {
  id?: string
  monthlyIncome: runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross: runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate: runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax: runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome: runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: boolean
  citExemption?: string
  createdAt?: Date | string
}

export type TaxProfileUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  citExemption?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaxProfileUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  citExemption?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaxProfileUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  annualGross?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rentPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  pensionRate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  computedTax?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  netIncome?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  citExemption?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TaxProfileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  monthlyIncome?: boolean
  annualGross?: boolean
  rentPaid?: boolean
  pensionRate?: boolean
  computedTax?: boolean
  netIncome?: boolean
  isExempt?: boolean
  citExemption?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taxProfile"]>

export type TaxProfileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  monthlyIncome?: boolean
  annualGross?: boolean
  rentPaid?: boolean
  pensionRate?: boolean
  computedTax?: boolean
  netIncome?: boolean
  isExempt?: boolean
  citExemption?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taxProfile"]>

export type TaxProfileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  monthlyIncome?: boolean
  annualGross?: boolean
  rentPaid?: boolean
  pensionRate?: boolean
  computedTax?: boolean
  netIncome?: boolean
  isExempt?: boolean
  citExemption?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taxProfile"]>

export type TaxProfileSelectScalar = {
  id?: boolean
  userId?: boolean
  monthlyIncome?: boolean
  annualGross?: boolean
  rentPaid?: boolean
  pensionRate?: boolean
  computedTax?: boolean
  netIncome?: boolean
  isExempt?: boolean
  citExemption?: boolean
  createdAt?: boolean
}

export type TaxProfileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "monthlyIncome" | "annualGross" | "rentPaid" | "pensionRate" | "computedTax" | "netIncome" | "isExempt" | "citExemption" | "createdAt", ExtArgs["result"]["taxProfile"]>
export type TaxProfileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TaxProfileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TaxProfileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $TaxProfilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TaxProfile"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    monthlyIncome: runtime.Decimal
    annualGross: runtime.Decimal
    rentPaid: runtime.Decimal
    pensionRate: runtime.Decimal
    computedTax: runtime.Decimal
    netIncome: runtime.Decimal
    isExempt: boolean
    citExemption: string
    createdAt: Date
  }, ExtArgs["result"]["taxProfile"]>
  composites: {}
}

export type TaxProfileGetPayload<S extends boolean | null | undefined | TaxProfileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TaxProfilePayload, S>

export type TaxProfileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TaxProfileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TaxProfileCountAggregateInputType | true
  }

export interface TaxProfileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TaxProfile'], meta: { name: 'TaxProfile' } }
  /**
   * Find zero or one TaxProfile that matches the filter.
   * @param {TaxProfileFindUniqueArgs} args - Arguments to find a TaxProfile
   * @example
   * // Get one TaxProfile
   * const taxProfile = await prisma.taxProfile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TaxProfileFindUniqueArgs>(args: Prisma.SelectSubset<T, TaxProfileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TaxProfileClient<runtime.Types.Result.GetResult<Prisma.$TaxProfilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TaxProfile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TaxProfileFindUniqueOrThrowArgs} args - Arguments to find a TaxProfile
   * @example
   * // Get one TaxProfile
   * const taxProfile = await prisma.taxProfile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TaxProfileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TaxProfileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaxProfileClient<runtime.Types.Result.GetResult<Prisma.$TaxProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaxProfile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxProfileFindFirstArgs} args - Arguments to find a TaxProfile
   * @example
   * // Get one TaxProfile
   * const taxProfile = await prisma.taxProfile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TaxProfileFindFirstArgs>(args?: Prisma.SelectSubset<T, TaxProfileFindFirstArgs<ExtArgs>>): Prisma.Prisma__TaxProfileClient<runtime.Types.Result.GetResult<Prisma.$TaxProfilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaxProfile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxProfileFindFirstOrThrowArgs} args - Arguments to find a TaxProfile
   * @example
   * // Get one TaxProfile
   * const taxProfile = await prisma.taxProfile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TaxProfileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TaxProfileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaxProfileClient<runtime.Types.Result.GetResult<Prisma.$TaxProfilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TaxProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TaxProfiles
   * const taxProfiles = await prisma.taxProfile.findMany()
   * 
   * // Get first 10 TaxProfiles
   * const taxProfiles = await prisma.taxProfile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const taxProfileWithIdOnly = await prisma.taxProfile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TaxProfileFindManyArgs>(args?: Prisma.SelectSubset<T, TaxProfileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaxProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TaxProfile.
   * @param {TaxProfileCreateArgs} args - Arguments to create a TaxProfile.
   * @example
   * // Create one TaxProfile
   * const TaxProfile = await prisma.taxProfile.create({
   *   data: {
   *     // ... data to create a TaxProfile
   *   }
   * })
   * 
   */
  create<T extends TaxProfileCreateArgs>(args: Prisma.SelectSubset<T, TaxProfileCreateArgs<ExtArgs>>): Prisma.Prisma__TaxProfileClient<runtime.Types.Result.GetResult<Prisma.$TaxProfilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TaxProfiles.
   * @param {TaxProfileCreateManyArgs} args - Arguments to create many TaxProfiles.
   * @example
   * // Create many TaxProfiles
   * const taxProfile = await prisma.taxProfile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TaxProfileCreateManyArgs>(args?: Prisma.SelectSubset<T, TaxProfileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TaxProfiles and returns the data saved in the database.
   * @param {TaxProfileCreateManyAndReturnArgs} args - Arguments to create many TaxProfiles.
   * @example
   * // Create many TaxProfiles
   * const taxProfile = await prisma.taxProfile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TaxProfiles and only return the `id`
   * const taxProfileWithIdOnly = await prisma.taxProfile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TaxProfileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TaxProfileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaxProfilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TaxProfile.
   * @param {TaxProfileDeleteArgs} args - Arguments to delete one TaxProfile.
   * @example
   * // Delete one TaxProfile
   * const TaxProfile = await prisma.taxProfile.delete({
   *   where: {
   *     // ... filter to delete one TaxProfile
   *   }
   * })
   * 
   */
  delete<T extends TaxProfileDeleteArgs>(args: Prisma.SelectSubset<T, TaxProfileDeleteArgs<ExtArgs>>): Prisma.Prisma__TaxProfileClient<runtime.Types.Result.GetResult<Prisma.$TaxProfilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TaxProfile.
   * @param {TaxProfileUpdateArgs} args - Arguments to update one TaxProfile.
   * @example
   * // Update one TaxProfile
   * const taxProfile = await prisma.taxProfile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TaxProfileUpdateArgs>(args: Prisma.SelectSubset<T, TaxProfileUpdateArgs<ExtArgs>>): Prisma.Prisma__TaxProfileClient<runtime.Types.Result.GetResult<Prisma.$TaxProfilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TaxProfiles.
   * @param {TaxProfileDeleteManyArgs} args - Arguments to filter TaxProfiles to delete.
   * @example
   * // Delete a few TaxProfiles
   * const { count } = await prisma.taxProfile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TaxProfileDeleteManyArgs>(args?: Prisma.SelectSubset<T, TaxProfileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaxProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TaxProfiles
   * const taxProfile = await prisma.taxProfile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TaxProfileUpdateManyArgs>(args: Prisma.SelectSubset<T, TaxProfileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaxProfiles and returns the data updated in the database.
   * @param {TaxProfileUpdateManyAndReturnArgs} args - Arguments to update many TaxProfiles.
   * @example
   * // Update many TaxProfiles
   * const taxProfile = await prisma.taxProfile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TaxProfiles and only return the `id`
   * const taxProfileWithIdOnly = await prisma.taxProfile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TaxProfileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TaxProfileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaxProfilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TaxProfile.
   * @param {TaxProfileUpsertArgs} args - Arguments to update or create a TaxProfile.
   * @example
   * // Update or create a TaxProfile
   * const taxProfile = await prisma.taxProfile.upsert({
   *   create: {
   *     // ... data to create a TaxProfile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TaxProfile we want to update
   *   }
   * })
   */
  upsert<T extends TaxProfileUpsertArgs>(args: Prisma.SelectSubset<T, TaxProfileUpsertArgs<ExtArgs>>): Prisma.Prisma__TaxProfileClient<runtime.Types.Result.GetResult<Prisma.$TaxProfilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TaxProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxProfileCountArgs} args - Arguments to filter TaxProfiles to count.
   * @example
   * // Count the number of TaxProfiles
   * const count = await prisma.taxProfile.count({
   *   where: {
   *     // ... the filter for the TaxProfiles we want to count
   *   }
   * })
  **/
  count<T extends TaxProfileCountArgs>(
    args?: Prisma.Subset<T, TaxProfileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TaxProfileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TaxProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TaxProfileAggregateArgs>(args: Prisma.Subset<T, TaxProfileAggregateArgs>): Prisma.PrismaPromise<GetTaxProfileAggregateType<T>>

  /**
   * Group by TaxProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TaxProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TaxProfileGroupByArgs['orderBy'] }
      : { orderBy?: TaxProfileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TaxProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTaxProfileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TaxProfile model
 */
readonly fields: TaxProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TaxProfile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TaxProfileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TaxProfile model
 */
export interface TaxProfileFieldRefs {
  readonly id: Prisma.FieldRef<"TaxProfile", 'String'>
  readonly userId: Prisma.FieldRef<"TaxProfile", 'String'>
  readonly monthlyIncome: Prisma.FieldRef<"TaxProfile", 'Decimal'>
  readonly annualGross: Prisma.FieldRef<"TaxProfile", 'Decimal'>
  readonly rentPaid: Prisma.FieldRef<"TaxProfile", 'Decimal'>
  readonly pensionRate: Prisma.FieldRef<"TaxProfile", 'Decimal'>
  readonly computedTax: Prisma.FieldRef<"TaxProfile", 'Decimal'>
  readonly netIncome: Prisma.FieldRef<"TaxProfile", 'Decimal'>
  readonly isExempt: Prisma.FieldRef<"TaxProfile", 'Boolean'>
  readonly citExemption: Prisma.FieldRef<"TaxProfile", 'String'>
  readonly createdAt: Prisma.FieldRef<"TaxProfile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TaxProfile findUnique
 */
export type TaxProfileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxProfile
   */
  select?: Prisma.TaxProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxProfile
   */
  omit?: Prisma.TaxProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxProfileInclude<ExtArgs> | null
  /**
   * Filter, which TaxProfile to fetch.
   */
  where: Prisma.TaxProfileWhereUniqueInput
}

/**
 * TaxProfile findUniqueOrThrow
 */
export type TaxProfileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxProfile
   */
  select?: Prisma.TaxProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxProfile
   */
  omit?: Prisma.TaxProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxProfileInclude<ExtArgs> | null
  /**
   * Filter, which TaxProfile to fetch.
   */
  where: Prisma.TaxProfileWhereUniqueInput
}

/**
 * TaxProfile findFirst
 */
export type TaxProfileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxProfile
   */
  select?: Prisma.TaxProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxProfile
   */
  omit?: Prisma.TaxProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxProfileInclude<ExtArgs> | null
  /**
   * Filter, which TaxProfile to fetch.
   */
  where?: Prisma.TaxProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxProfiles to fetch.
   */
  orderBy?: Prisma.TaxProfileOrderByWithRelationInput | Prisma.TaxProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaxProfiles.
   */
  cursor?: Prisma.TaxProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaxProfiles.
   */
  distinct?: Prisma.TaxProfileScalarFieldEnum | Prisma.TaxProfileScalarFieldEnum[]
}

/**
 * TaxProfile findFirstOrThrow
 */
export type TaxProfileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxProfile
   */
  select?: Prisma.TaxProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxProfile
   */
  omit?: Prisma.TaxProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxProfileInclude<ExtArgs> | null
  /**
   * Filter, which TaxProfile to fetch.
   */
  where?: Prisma.TaxProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxProfiles to fetch.
   */
  orderBy?: Prisma.TaxProfileOrderByWithRelationInput | Prisma.TaxProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaxProfiles.
   */
  cursor?: Prisma.TaxProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaxProfiles.
   */
  distinct?: Prisma.TaxProfileScalarFieldEnum | Prisma.TaxProfileScalarFieldEnum[]
}

/**
 * TaxProfile findMany
 */
export type TaxProfileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxProfile
   */
  select?: Prisma.TaxProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxProfile
   */
  omit?: Prisma.TaxProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxProfileInclude<ExtArgs> | null
  /**
   * Filter, which TaxProfiles to fetch.
   */
  where?: Prisma.TaxProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxProfiles to fetch.
   */
  orderBy?: Prisma.TaxProfileOrderByWithRelationInput | Prisma.TaxProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TaxProfiles.
   */
  cursor?: Prisma.TaxProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaxProfiles.
   */
  distinct?: Prisma.TaxProfileScalarFieldEnum | Prisma.TaxProfileScalarFieldEnum[]
}

/**
 * TaxProfile create
 */
export type TaxProfileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxProfile
   */
  select?: Prisma.TaxProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxProfile
   */
  omit?: Prisma.TaxProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxProfileInclude<ExtArgs> | null
  /**
   * The data needed to create a TaxProfile.
   */
  data: Prisma.XOR<Prisma.TaxProfileCreateInput, Prisma.TaxProfileUncheckedCreateInput>
}

/**
 * TaxProfile createMany
 */
export type TaxProfileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TaxProfiles.
   */
  data: Prisma.TaxProfileCreateManyInput | Prisma.TaxProfileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TaxProfile createManyAndReturn
 */
export type TaxProfileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxProfile
   */
  select?: Prisma.TaxProfileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaxProfile
   */
  omit?: Prisma.TaxProfileOmit<ExtArgs> | null
  /**
   * The data used to create many TaxProfiles.
   */
  data: Prisma.TaxProfileCreateManyInput | Prisma.TaxProfileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxProfileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TaxProfile update
 */
export type TaxProfileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxProfile
   */
  select?: Prisma.TaxProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxProfile
   */
  omit?: Prisma.TaxProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxProfileInclude<ExtArgs> | null
  /**
   * The data needed to update a TaxProfile.
   */
  data: Prisma.XOR<Prisma.TaxProfileUpdateInput, Prisma.TaxProfileUncheckedUpdateInput>
  /**
   * Choose, which TaxProfile to update.
   */
  where: Prisma.TaxProfileWhereUniqueInput
}

/**
 * TaxProfile updateMany
 */
export type TaxProfileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TaxProfiles.
   */
  data: Prisma.XOR<Prisma.TaxProfileUpdateManyMutationInput, Prisma.TaxProfileUncheckedUpdateManyInput>
  /**
   * Filter which TaxProfiles to update
   */
  where?: Prisma.TaxProfileWhereInput
  /**
   * Limit how many TaxProfiles to update.
   */
  limit?: number
}

/**
 * TaxProfile updateManyAndReturn
 */
export type TaxProfileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxProfile
   */
  select?: Prisma.TaxProfileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaxProfile
   */
  omit?: Prisma.TaxProfileOmit<ExtArgs> | null
  /**
   * The data used to update TaxProfiles.
   */
  data: Prisma.XOR<Prisma.TaxProfileUpdateManyMutationInput, Prisma.TaxProfileUncheckedUpdateManyInput>
  /**
   * Filter which TaxProfiles to update
   */
  where?: Prisma.TaxProfileWhereInput
  /**
   * Limit how many TaxProfiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxProfileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TaxProfile upsert
 */
export type TaxProfileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxProfile
   */
  select?: Prisma.TaxProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxProfile
   */
  omit?: Prisma.TaxProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxProfileInclude<ExtArgs> | null
  /**
   * The filter to search for the TaxProfile to update in case it exists.
   */
  where: Prisma.TaxProfileWhereUniqueInput
  /**
   * In case the TaxProfile found by the `where` argument doesn't exist, create a new TaxProfile with this data.
   */
  create: Prisma.XOR<Prisma.TaxProfileCreateInput, Prisma.TaxProfileUncheckedCreateInput>
  /**
   * In case the TaxProfile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TaxProfileUpdateInput, Prisma.TaxProfileUncheckedUpdateInput>
}

/**
 * TaxProfile delete
 */
export type TaxProfileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxProfile
   */
  select?: Prisma.TaxProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxProfile
   */
  omit?: Prisma.TaxProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxProfileInclude<ExtArgs> | null
  /**
   * Filter which TaxProfile to delete.
   */
  where: Prisma.TaxProfileWhereUniqueInput
}

/**
 * TaxProfile deleteMany
 */
export type TaxProfileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaxProfiles to delete
   */
  where?: Prisma.TaxProfileWhereInput
  /**
   * Limit how many TaxProfiles to delete.
   */
  limit?: number
}

/**
 * TaxProfile without action
 */
export type TaxProfileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxProfile
   */
  select?: Prisma.TaxProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxProfile
   */
  omit?: Prisma.TaxProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxProfileInclude<ExtArgs> | null
}
