
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VatItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model VatItem
 * 
 */
export type VatItemModel = runtime.Types.Result.DefaultSelection<Prisma.$VatItemPayload>

export type AggregateVatItem = {
  _count: VatItemCountAggregateOutputType | null
  _avg: VatItemAvgAggregateOutputType | null
  _sum: VatItemSumAggregateOutputType | null
  _min: VatItemMinAggregateOutputType | null
  _max: VatItemMaxAggregateOutputType | null
}

export type VatItemAvgAggregateOutputType = {
  rate: runtime.Decimal | null
}

export type VatItemSumAggregateOutputType = {
  rate: runtime.Decimal | null
}

export type VatItemMinAggregateOutputType = {
  id: string | null
  name: string | null
  category: string | null
  status: string | null
  rate: runtime.Decimal | null
  createdAt: Date | null
}

export type VatItemMaxAggregateOutputType = {
  id: string | null
  name: string | null
  category: string | null
  status: string | null
  rate: runtime.Decimal | null
  createdAt: Date | null
}

export type VatItemCountAggregateOutputType = {
  id: number
  name: number
  category: number
  status: number
  rate: number
  createdAt: number
  _all: number
}


export type VatItemAvgAggregateInputType = {
  rate?: true
}

export type VatItemSumAggregateInputType = {
  rate?: true
}

export type VatItemMinAggregateInputType = {
  id?: true
  name?: true
  category?: true
  status?: true
  rate?: true
  createdAt?: true
}

export type VatItemMaxAggregateInputType = {
  id?: true
  name?: true
  category?: true
  status?: true
  rate?: true
  createdAt?: true
}

export type VatItemCountAggregateInputType = {
  id?: true
  name?: true
  category?: true
  status?: true
  rate?: true
  createdAt?: true
  _all?: true
}

export type VatItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VatItem to aggregate.
   */
  where?: Prisma.VatItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VatItems to fetch.
   */
  orderBy?: Prisma.VatItemOrderByWithRelationInput | Prisma.VatItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VatItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VatItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VatItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VatItems
  **/
  _count?: true | VatItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VatItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VatItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VatItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VatItemMaxAggregateInputType
}

export type GetVatItemAggregateType<T extends VatItemAggregateArgs> = {
      [P in keyof T & keyof AggregateVatItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVatItem[P]>
    : Prisma.GetScalarType<T[P], AggregateVatItem[P]>
}




export type VatItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VatItemWhereInput
  orderBy?: Prisma.VatItemOrderByWithAggregationInput | Prisma.VatItemOrderByWithAggregationInput[]
  by: Prisma.VatItemScalarFieldEnum[] | Prisma.VatItemScalarFieldEnum
  having?: Prisma.VatItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VatItemCountAggregateInputType | true
  _avg?: VatItemAvgAggregateInputType
  _sum?: VatItemSumAggregateInputType
  _min?: VatItemMinAggregateInputType
  _max?: VatItemMaxAggregateInputType
}

export type VatItemGroupByOutputType = {
  id: string
  name: string
  category: string
  status: string
  rate: runtime.Decimal
  createdAt: Date
  _count: VatItemCountAggregateOutputType | null
  _avg: VatItemAvgAggregateOutputType | null
  _sum: VatItemSumAggregateOutputType | null
  _min: VatItemMinAggregateOutputType | null
  _max: VatItemMaxAggregateOutputType | null
}

export type GetVatItemGroupByPayload<T extends VatItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VatItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VatItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VatItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VatItemGroupByOutputType[P]>
      }
    >
  >



export type VatItemWhereInput = {
  AND?: Prisma.VatItemWhereInput | Prisma.VatItemWhereInput[]
  OR?: Prisma.VatItemWhereInput[]
  NOT?: Prisma.VatItemWhereInput | Prisma.VatItemWhereInput[]
  id?: Prisma.StringFilter<"VatItem"> | string
  name?: Prisma.StringFilter<"VatItem"> | string
  category?: Prisma.StringFilter<"VatItem"> | string
  status?: Prisma.StringFilter<"VatItem"> | string
  rate?: Prisma.DecimalFilter<"VatItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"VatItem"> | Date | string
}

export type VatItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type VatItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.VatItemWhereInput | Prisma.VatItemWhereInput[]
  OR?: Prisma.VatItemWhereInput[]
  NOT?: Prisma.VatItemWhereInput | Prisma.VatItemWhereInput[]
  category?: Prisma.StringFilter<"VatItem"> | string
  status?: Prisma.StringFilter<"VatItem"> | string
  rate?: Prisma.DecimalFilter<"VatItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"VatItem"> | Date | string
}, "id" | "name">

export type VatItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.VatItemCountOrderByAggregateInput
  _avg?: Prisma.VatItemAvgOrderByAggregateInput
  _max?: Prisma.VatItemMaxOrderByAggregateInput
  _min?: Prisma.VatItemMinOrderByAggregateInput
  _sum?: Prisma.VatItemSumOrderByAggregateInput
}

export type VatItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.VatItemScalarWhereWithAggregatesInput | Prisma.VatItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.VatItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VatItemScalarWhereWithAggregatesInput | Prisma.VatItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VatItem"> | string
  name?: Prisma.StringWithAggregatesFilter<"VatItem"> | string
  category?: Prisma.StringWithAggregatesFilter<"VatItem"> | string
  status?: Prisma.StringWithAggregatesFilter<"VatItem"> | string
  rate?: Prisma.DecimalWithAggregatesFilter<"VatItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"VatItem"> | Date | string
}

export type VatItemCreateInput = {
  id?: string
  name: string
  category: string
  status: string
  rate: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type VatItemUncheckedCreateInput = {
  id?: string
  name: string
  category: string
  status: string
  rate: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type VatItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VatItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VatItemCreateManyInput = {
  id?: string
  name: string
  category: string
  status: string
  rate: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type VatItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VatItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  rate?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VatItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type VatItemAvgOrderByAggregateInput = {
  rate?: Prisma.SortOrder
}

export type VatItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type VatItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type VatItemSumOrderByAggregateInput = {
  rate?: Prisma.SortOrder
}



export type VatItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  category?: boolean
  status?: boolean
  rate?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["vatItem"]>

export type VatItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  category?: boolean
  status?: boolean
  rate?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["vatItem"]>

export type VatItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  category?: boolean
  status?: boolean
  rate?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["vatItem"]>

export type VatItemSelectScalar = {
  id?: boolean
  name?: boolean
  category?: boolean
  status?: boolean
  rate?: boolean
  createdAt?: boolean
}

export type VatItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "category" | "status" | "rate" | "createdAt", ExtArgs["result"]["vatItem"]>

export type $VatItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VatItem"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    category: string
    status: string
    rate: runtime.Decimal
    createdAt: Date
  }, ExtArgs["result"]["vatItem"]>
  composites: {}
}

export type VatItemGetPayload<S extends boolean | null | undefined | VatItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VatItemPayload, S>

export type VatItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VatItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VatItemCountAggregateInputType | true
  }

export interface VatItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VatItem'], meta: { name: 'VatItem' } }
  /**
   * Find zero or one VatItem that matches the filter.
   * @param {VatItemFindUniqueArgs} args - Arguments to find a VatItem
   * @example
   * // Get one VatItem
   * const vatItem = await prisma.vatItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VatItemFindUniqueArgs>(args: Prisma.SelectSubset<T, VatItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VatItemClient<runtime.Types.Result.GetResult<Prisma.$VatItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VatItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VatItemFindUniqueOrThrowArgs} args - Arguments to find a VatItem
   * @example
   * // Get one VatItem
   * const vatItem = await prisma.vatItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VatItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VatItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VatItemClient<runtime.Types.Result.GetResult<Prisma.$VatItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VatItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VatItemFindFirstArgs} args - Arguments to find a VatItem
   * @example
   * // Get one VatItem
   * const vatItem = await prisma.vatItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VatItemFindFirstArgs>(args?: Prisma.SelectSubset<T, VatItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__VatItemClient<runtime.Types.Result.GetResult<Prisma.$VatItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VatItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VatItemFindFirstOrThrowArgs} args - Arguments to find a VatItem
   * @example
   * // Get one VatItem
   * const vatItem = await prisma.vatItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VatItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VatItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VatItemClient<runtime.Types.Result.GetResult<Prisma.$VatItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VatItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VatItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VatItems
   * const vatItems = await prisma.vatItem.findMany()
   * 
   * // Get first 10 VatItems
   * const vatItems = await prisma.vatItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const vatItemWithIdOnly = await prisma.vatItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VatItemFindManyArgs>(args?: Prisma.SelectSubset<T, VatItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VatItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VatItem.
   * @param {VatItemCreateArgs} args - Arguments to create a VatItem.
   * @example
   * // Create one VatItem
   * const VatItem = await prisma.vatItem.create({
   *   data: {
   *     // ... data to create a VatItem
   *   }
   * })
   * 
   */
  create<T extends VatItemCreateArgs>(args: Prisma.SelectSubset<T, VatItemCreateArgs<ExtArgs>>): Prisma.Prisma__VatItemClient<runtime.Types.Result.GetResult<Prisma.$VatItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VatItems.
   * @param {VatItemCreateManyArgs} args - Arguments to create many VatItems.
   * @example
   * // Create many VatItems
   * const vatItem = await prisma.vatItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VatItemCreateManyArgs>(args?: Prisma.SelectSubset<T, VatItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VatItems and returns the data saved in the database.
   * @param {VatItemCreateManyAndReturnArgs} args - Arguments to create many VatItems.
   * @example
   * // Create many VatItems
   * const vatItem = await prisma.vatItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VatItems and only return the `id`
   * const vatItemWithIdOnly = await prisma.vatItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VatItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VatItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VatItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VatItem.
   * @param {VatItemDeleteArgs} args - Arguments to delete one VatItem.
   * @example
   * // Delete one VatItem
   * const VatItem = await prisma.vatItem.delete({
   *   where: {
   *     // ... filter to delete one VatItem
   *   }
   * })
   * 
   */
  delete<T extends VatItemDeleteArgs>(args: Prisma.SelectSubset<T, VatItemDeleteArgs<ExtArgs>>): Prisma.Prisma__VatItemClient<runtime.Types.Result.GetResult<Prisma.$VatItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VatItem.
   * @param {VatItemUpdateArgs} args - Arguments to update one VatItem.
   * @example
   * // Update one VatItem
   * const vatItem = await prisma.vatItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VatItemUpdateArgs>(args: Prisma.SelectSubset<T, VatItemUpdateArgs<ExtArgs>>): Prisma.Prisma__VatItemClient<runtime.Types.Result.GetResult<Prisma.$VatItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VatItems.
   * @param {VatItemDeleteManyArgs} args - Arguments to filter VatItems to delete.
   * @example
   * // Delete a few VatItems
   * const { count } = await prisma.vatItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VatItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, VatItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VatItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VatItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VatItems
   * const vatItem = await prisma.vatItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VatItemUpdateManyArgs>(args: Prisma.SelectSubset<T, VatItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VatItems and returns the data updated in the database.
   * @param {VatItemUpdateManyAndReturnArgs} args - Arguments to update many VatItems.
   * @example
   * // Update many VatItems
   * const vatItem = await prisma.vatItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VatItems and only return the `id`
   * const vatItemWithIdOnly = await prisma.vatItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VatItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VatItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VatItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VatItem.
   * @param {VatItemUpsertArgs} args - Arguments to update or create a VatItem.
   * @example
   * // Update or create a VatItem
   * const vatItem = await prisma.vatItem.upsert({
   *   create: {
   *     // ... data to create a VatItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VatItem we want to update
   *   }
   * })
   */
  upsert<T extends VatItemUpsertArgs>(args: Prisma.SelectSubset<T, VatItemUpsertArgs<ExtArgs>>): Prisma.Prisma__VatItemClient<runtime.Types.Result.GetResult<Prisma.$VatItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VatItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VatItemCountArgs} args - Arguments to filter VatItems to count.
   * @example
   * // Count the number of VatItems
   * const count = await prisma.vatItem.count({
   *   where: {
   *     // ... the filter for the VatItems we want to count
   *   }
   * })
  **/
  count<T extends VatItemCountArgs>(
    args?: Prisma.Subset<T, VatItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VatItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VatItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VatItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VatItemAggregateArgs>(args: Prisma.Subset<T, VatItemAggregateArgs>): Prisma.PrismaPromise<GetVatItemAggregateType<T>>

  /**
   * Group by VatItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VatItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VatItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VatItemGroupByArgs['orderBy'] }
      : { orderBy?: VatItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VatItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVatItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VatItem model
 */
readonly fields: VatItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VatItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VatItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VatItem model
 */
export interface VatItemFieldRefs {
  readonly id: Prisma.FieldRef<"VatItem", 'String'>
  readonly name: Prisma.FieldRef<"VatItem", 'String'>
  readonly category: Prisma.FieldRef<"VatItem", 'String'>
  readonly status: Prisma.FieldRef<"VatItem", 'String'>
  readonly rate: Prisma.FieldRef<"VatItem", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"VatItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * VatItem findUnique
 */
export type VatItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VatItem
   */
  select?: Prisma.VatItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VatItem
   */
  omit?: Prisma.VatItemOmit<ExtArgs> | null
  /**
   * Filter, which VatItem to fetch.
   */
  where: Prisma.VatItemWhereUniqueInput
}

/**
 * VatItem findUniqueOrThrow
 */
export type VatItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VatItem
   */
  select?: Prisma.VatItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VatItem
   */
  omit?: Prisma.VatItemOmit<ExtArgs> | null
  /**
   * Filter, which VatItem to fetch.
   */
  where: Prisma.VatItemWhereUniqueInput
}

/**
 * VatItem findFirst
 */
export type VatItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VatItem
   */
  select?: Prisma.VatItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VatItem
   */
  omit?: Prisma.VatItemOmit<ExtArgs> | null
  /**
   * Filter, which VatItem to fetch.
   */
  where?: Prisma.VatItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VatItems to fetch.
   */
  orderBy?: Prisma.VatItemOrderByWithRelationInput | Prisma.VatItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VatItems.
   */
  cursor?: Prisma.VatItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VatItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VatItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VatItems.
   */
  distinct?: Prisma.VatItemScalarFieldEnum | Prisma.VatItemScalarFieldEnum[]
}

/**
 * VatItem findFirstOrThrow
 */
export type VatItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VatItem
   */
  select?: Prisma.VatItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VatItem
   */
  omit?: Prisma.VatItemOmit<ExtArgs> | null
  /**
   * Filter, which VatItem to fetch.
   */
  where?: Prisma.VatItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VatItems to fetch.
   */
  orderBy?: Prisma.VatItemOrderByWithRelationInput | Prisma.VatItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VatItems.
   */
  cursor?: Prisma.VatItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VatItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VatItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VatItems.
   */
  distinct?: Prisma.VatItemScalarFieldEnum | Prisma.VatItemScalarFieldEnum[]
}

/**
 * VatItem findMany
 */
export type VatItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VatItem
   */
  select?: Prisma.VatItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VatItem
   */
  omit?: Prisma.VatItemOmit<ExtArgs> | null
  /**
   * Filter, which VatItems to fetch.
   */
  where?: Prisma.VatItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VatItems to fetch.
   */
  orderBy?: Prisma.VatItemOrderByWithRelationInput | Prisma.VatItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VatItems.
   */
  cursor?: Prisma.VatItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VatItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VatItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VatItems.
   */
  distinct?: Prisma.VatItemScalarFieldEnum | Prisma.VatItemScalarFieldEnum[]
}

/**
 * VatItem create
 */
export type VatItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VatItem
   */
  select?: Prisma.VatItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VatItem
   */
  omit?: Prisma.VatItemOmit<ExtArgs> | null
  /**
   * The data needed to create a VatItem.
   */
  data: Prisma.XOR<Prisma.VatItemCreateInput, Prisma.VatItemUncheckedCreateInput>
}

/**
 * VatItem createMany
 */
export type VatItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VatItems.
   */
  data: Prisma.VatItemCreateManyInput | Prisma.VatItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VatItem createManyAndReturn
 */
export type VatItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VatItem
   */
  select?: Prisma.VatItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VatItem
   */
  omit?: Prisma.VatItemOmit<ExtArgs> | null
  /**
   * The data used to create many VatItems.
   */
  data: Prisma.VatItemCreateManyInput | Prisma.VatItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VatItem update
 */
export type VatItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VatItem
   */
  select?: Prisma.VatItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VatItem
   */
  omit?: Prisma.VatItemOmit<ExtArgs> | null
  /**
   * The data needed to update a VatItem.
   */
  data: Prisma.XOR<Prisma.VatItemUpdateInput, Prisma.VatItemUncheckedUpdateInput>
  /**
   * Choose, which VatItem to update.
   */
  where: Prisma.VatItemWhereUniqueInput
}

/**
 * VatItem updateMany
 */
export type VatItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VatItems.
   */
  data: Prisma.XOR<Prisma.VatItemUpdateManyMutationInput, Prisma.VatItemUncheckedUpdateManyInput>
  /**
   * Filter which VatItems to update
   */
  where?: Prisma.VatItemWhereInput
  /**
   * Limit how many VatItems to update.
   */
  limit?: number
}

/**
 * VatItem updateManyAndReturn
 */
export type VatItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VatItem
   */
  select?: Prisma.VatItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VatItem
   */
  omit?: Prisma.VatItemOmit<ExtArgs> | null
  /**
   * The data used to update VatItems.
   */
  data: Prisma.XOR<Prisma.VatItemUpdateManyMutationInput, Prisma.VatItemUncheckedUpdateManyInput>
  /**
   * Filter which VatItems to update
   */
  where?: Prisma.VatItemWhereInput
  /**
   * Limit how many VatItems to update.
   */
  limit?: number
}

/**
 * VatItem upsert
 */
export type VatItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VatItem
   */
  select?: Prisma.VatItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VatItem
   */
  omit?: Prisma.VatItemOmit<ExtArgs> | null
  /**
   * The filter to search for the VatItem to update in case it exists.
   */
  where: Prisma.VatItemWhereUniqueInput
  /**
   * In case the VatItem found by the `where` argument doesn't exist, create a new VatItem with this data.
   */
  create: Prisma.XOR<Prisma.VatItemCreateInput, Prisma.VatItemUncheckedCreateInput>
  /**
   * In case the VatItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VatItemUpdateInput, Prisma.VatItemUncheckedUpdateInput>
}

/**
 * VatItem delete
 */
export type VatItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VatItem
   */
  select?: Prisma.VatItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VatItem
   */
  omit?: Prisma.VatItemOmit<ExtArgs> | null
  /**
   * Filter which VatItem to delete.
   */
  where: Prisma.VatItemWhereUniqueInput
}

/**
 * VatItem deleteMany
 */
export type VatItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VatItems to delete
   */
  where?: Prisma.VatItemWhereInput
  /**
   * Limit how many VatItems to delete.
   */
  limit?: number
}

/**
 * VatItem without action
 */
export type VatItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VatItem
   */
  select?: Prisma.VatItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VatItem
   */
  omit?: Prisma.VatItemOmit<ExtArgs> | null
}
