
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model TaxProfile
 * 
 */
export type TaxProfile = Prisma.TaxProfileModel
/**
 * Model VatItem
 * 
 */
export type VatItem = Prisma.VatItemModel
/**
 * Model QuizQuestion
 * 
 */
export type QuizQuestion = Prisma.QuizQuestionModel
/**
 * Model QuizScore
 * 
 */
export type QuizScore = Prisma.QuizScoreModel
/**
 * Model ChatSession
 * 
 */
export type ChatSession = Prisma.ChatSessionModel
/**
 * Model ChatMessage
 * 
 */
export type ChatMessage = Prisma.ChatMessageModel
/**
 * Model ForumTopic
 * 
 */
export type ForumTopic = Prisma.ForumTopicModel
/**
 * Model ForumReply
 * 
 */
export type ForumReply = Prisma.ForumReplyModel
/**
 * Model TaxArticle
 * 
 */
export type TaxArticle = Prisma.TaxArticleModel
