import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/tax_profile.dart';

class PdfService {
  static final _naira =
      NumberFormat.currency(locale: 'en_NG', symbol: '₦', decimalDigits: 2);

  static Future<void> exportTaxReport(TaxProfile profile) async {
    final doc = pw.Document();
    final font = await PdfGoogleFonts.interRegular();
    final boldFont = await PdfGoogleFonts.interBold();

    doc.addPage(
      pw.MultiPage(
        theme: pw.ThemeData.withFont(base: font, bold: boldFont),
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (_) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('NaijaTax Enlighten',
                      style: pw.TextStyle(
                          font: boldFont,
                          fontSize: 20,
                          color: PdfColor.fromHex('#00288E'))),
                  pw.Text('Tax Assessment Report',
                      style: pw.TextStyle(
                          fontSize: 12, color: PdfColor.fromHex('#444653'))),
                ]),
            pw.Divider(color: PdfColor.fromHex('#C4C5D5')),
            pw.SizedBox(height: 4),
          ],
        ),
        footer: (_) => pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                  'Generated by NaijaTax Enlighten · ${DateFormat.yMMMd().format(DateTime.now())}',
                  style: const pw.TextStyle(fontSize: 10)),
              pw.Text('For educational purposes only. Not official tax advice.',
                  style: const pw.TextStyle(fontSize: 10)),
            ]),
        build: (_) => [
          pw.SizedBox(height: 16),
          pw.Text('Personal Income Tax (PAYE) Summary',
              style: pw.TextStyle(font: boldFont, fontSize: 16)),
          pw.SizedBox(height: 12),
          _summaryRow(
              'Monthly Income', _naira.format(profile.monthlyIncome), boldFont),
          _summaryRow('Annual Gross Income', _naira.format(profile.annualGross),
              boldFont),
          _summaryRow('Pension Deduction (8%)',
              '- ${_naira.format(profile.pensionDeduction)}', boldFont),
          _summaryRow('Rent Relief', '- ${_naira.format(profile.rentRelief)}',
              boldFont),
          _summaryRow(
              'Taxable Income', _naira.format(profile.taxableIncome), boldFont),
          pw.Divider(color: PdfColor.fromHex('#C4C5D5')),
          _summaryRow('Total Tax Payable (PAYE)',
              _naira.format(profile.computedTax), boldFont,
              valueColor: PdfColor.fromHex('#B91C1C')),
          _summaryRow('Net Annual Income (Take-home)',
              _naira.format(profile.netIncome), boldFont,
              valueColor: PdfColor.fromHex('#15803D')),
          _summaryRow('Tax Savings (vs. Old Act)',
              _naira.format(profile.savings), boldFont,
              valueColor: PdfColor.fromHex('#0060AC')),
          pw.SizedBox(height: 20),
          pw.Text('Progressive Tax Breakdown (NTA 2025)',
              style: pw.TextStyle(font: boldFont, fontSize: 14)),
          pw.SizedBox(height: 8),
          pw.TableHelper.fromTextArray(
            headers: ['Bracket', 'Rate', 'Taxable Amount', 'Tax'],
            data: profile.breakdown
                .map((b) => [
                      b.bracket,
                      '${(b.rate * 100).toStringAsFixed(0)}%',
                      _naira.format(b.taxableAmount),
                      _naira.format(b.tax),
                    ])
                .toList(),
            headerStyle: pw.TextStyle(font: boldFont, color: PdfColors.white),
            headerDecoration:
                const pw.BoxDecoration(color: PdfColor.fromInt(0xFF00288E)),
            cellAlignments: {
              0: pw.Alignment.centerLeft,
              1: pw.Alignment.center,
              2: pw.Alignment.centerRight,
              3: pw.Alignment.centerRight,
            },
          ),
          pw.SizedBox(height: 20),
          pw.Text('Company Income Tax (CIT) Status',
              style: pw.TextStyle(font: boldFont, fontSize: 14)),
          pw.SizedBox(height: 8),
          pw.Text(profile.citExemption,
              style: pw.TextStyle(
                  fontSize: 12,
                  color: profile.citExemption.contains('EXEMPT')
                      ? PdfColor.fromHex('#15803D')
                      : PdfColor.fromHex('#B91C1C'))),
          pw.SizedBox(height: 20),
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#F1F3FF'),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8))),
            child: pw.Text(
              'Disclaimer: This report is generated for educational purposes and does not constitute professional tax advice. Please consult a registered tax practitioner for official filings.',
              style: pw.TextStyle(
                  fontSize: 10, color: PdfColor.fromHex('#444653')),
            ),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(onLayout: (format) async => doc.save());
  }

  static pw.Widget _summaryRow(String label, String value, pw.Font boldFont,
      {PdfColor? valueColor}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(label, style: const pw.TextStyle(fontSize: 12)),
            pw.Text(value,
                style: pw.TextStyle(
                    font: boldFont,
                    fontSize: 12,
                    color: valueColor ?? PdfColors.black)),
          ]),
    );
  }
}
